'use strict';
const {el,api,notice,key,link,badge,date}=WA;
const $=id=>document.getElementById(id);
const state={chat:null,chats:[],busy:false,loading:false,sendKey:'',createKey:key(),threadVersion:'',upgradeVersion:'',connectionLost:false,decision:null,replyKey:'',first:true};
$('today').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
function controls(){const busy=state.busy;const running=state.chat?.state==='GENERATING';$('send-chat').disabled=busy||running;$('new-chat').disabled=busy;$('chat-select').disabled=busy;$('stop-chat').hidden=!running;$('stop-chat').disabled=busy;$('generating').hidden=!running;if($('switch-chat-executor'))$('switch-chat-executor').disabled=busy||running||!state.homeBinding;document.querySelectorAll('[data-proposal-action],.dialog-actions button,.upgrade-actions button').forEach(b=>b.disabled=busy);const d=state.decision,blocked=busy||decisionChat.isBusy()||decisionChat.isWaiting()||decisionChat.hasDraft()||d?.review?.state!=='PENDING';$('decision-approve').disabled=blocked;$('decision-reject').disabled=blocked;decisionChat.controls(busy);}
async function action(fn){if(state.busy)return;state.busy=true;controls();notice('');try{await fn();}catch(e){notice(e.message,true);if($('decision-dialog').open){$('decision-error').hidden=false;$('decision-error').textContent=e.message;}}finally{state.busy=false;controls();}}
function setChat(c){state.chat=c;renderThread();renderHomeExecutor();controls();}
function starters(){const box=el('div',null,'chat-empty');box.append(el('div','✳','chat-avatar'),el('h2','今天，有什么可以一起推进？'),el('p','你可以了解工作进展，也可以交代新的事情。需要采取行动时，我会先把建议交给你确认。'));const prompts=el('div',null,'starter-list');for(const text of ['现在有哪些事情需要我决定？','帮我整理一份本周工作总结','我需要一个新的工作角色','给这个工作助手增加一个功能']){const b=el('button',text+'  ↗');b.onclick=()=>{$('home-message').value=text;$('home-message').focus();state.sendKey='';};prompts.append(b);}box.append(prompts);return box;}
function renderThread(){const c=state.chat,version=(c?.chat_id||'new')+':'+(c?.version||0);if(state.threadVersion===version)return;state.threadVersion=version;const box=$('chat-thread'),bottom=box.scrollTop+box.clientHeight>=box.scrollHeight-65;box.replaceChildren();if(!c?.messages.length)box.append(starters());for(const m of c?.messages||[]){const row=el('div',null,'chat-message '+m.speaker);row.append(el('span',(m.speaker==='user'?'你':m.speaker==='assistant'?'工作助理':'系统记录')+' · '+date(m.created_at_ms),'byline'),el('div',m.content));if(m.speaker==='assistant'){for(const p of c.proposals.filter(p=>p.run_id===m.run_id))row.append(proposalCard(p));}box.append(row);}if(bottom||c?.state==='GENERATING')box.scrollTop=box.scrollHeight;}
function proposalCard(p){
 const kinds={create_work:'创建工作',message_work:'追加工作要求',pause_work:'暂停工作',create_role:'准备角色草稿',upgrade_system:'准备候选升级'},card=el('section',null,'proposal-card');
 card.append(el('span',kinds[p.kind]||p.kind,'eyebrow'),el('h3',p.title),el('div',p.text,'proposal-body'));
 if(p.target_task_id)card.append(link('查看关联工作 →','/tasks#'+p.target_task_id,'small'));
 if(p.role_spec){const d=el('details');d.append(el('summary','查看角色职责与完整配置'),el('pre',JSON.stringify(p.role_spec,null,2)));card.append(d);}
 const meta={message_work:'确认后加入原 Session 的下一轮，不会立即打断。',create_role:'只创建草稿；仍需在成员管理页检查、发布并配置 Agent。',pause_work:'会请求中断当前运行并暂停调度；不会回滚已发生的操作。',upgrade_system:'第一次确认只让 AI 在隔离副本中修改并测试；安装和重启还要再次确认。'}[p.kind]||'确认后才创建工作，并按所选角色自动分派。';
 card.append(el('p',meta,'proposal-meta'));
 const actions=el('div',null,'proposal-buttons');
 if(p.state==='PENDING'){for(const [decision,title,cls] of [['CONFIRMED','确认'+(kinds[p.kind]||'执行'),'primary'],['DISMISSED','暂不执行','']]){const b=el('button',title,cls);b.dataset.proposalAction=p.proposal_id;b.onclick=()=>action(async()=>{setChat(await api('/home/chats/'+state.chat.chat_id+'/proposals/'+p.proposal_id,'POST',{decision}));await refreshOverview();});actions.append(b);}}
 else{actions.append(el('span',{CONFIRMED:'已确认执行',DISMISSED:'已忽略',SUPERSEDED:'后续对话已使这条建议失效'}[p.state]||p.state,'small muted'));if(p.resource_id){if(p.kind==='create_role')actions.append(link('打开角色草稿 →','/members#'+p.resource_id,'small'));else if(p.kind==='upgrade_system')actions.append(el('span','可在“系统进化”中查看进度','small muted'));else actions.append(link('查看工作 →','/tasks#'+p.resource_id,'small'));}}
 card.append(actions);return card;
}
function renderOverview(home,system,upgrades){const stamp=JSON.stringify([home,system.connected_runtimes,system.eligible_agents,upgrades]);if(state.overviewVersion===stamp)return;state.overviewVersion=stamp;const counts=home.counts,latestUpgrade=upgrades.upgrades?.[0],upgradeAttention=latestUpgrade?.state==='READY'?latestUpgrade:null,workWaiting=(counts.NEW||0)+(counts.WAITING_REVIEW||0)+(counts.WAITING_INPUT||0)+(counts.BLOCKED||0)+(counts.WAITING_AUTHORIZATION||0)+(counts.WAITING_ENVIRONMENT||0),waiting=workWaiting+(upgradeAttention?1:0),running=(counts.IN_PROGRESS||0)+(counts.QUEUED||0);$('home-summary').textContent=waiting?`${waiting} 件事需要你看一下${running?'，另有 '+running+' 件工作正在推进':'。'}`:running?`暂时没有需要你处理的事项，${running} 件工作正在推进。`:'暂时没有待处理的决定。交代一件事，或问问最近的进展。';$('attention-count').textContent=waiting;const inbox=$('inbox');inbox.replaceChildren();if(upgradeAttention){const c=el('article',null,'card inbox-card');c.dataset.state='WAITING_REVIEW';c.append(el('span','候选升级待确认','status-pill'),el('h3',upgradeAttention.title),el('p',upgradeAttention.summary||'候选版本已经通过自动测试，请查看具体代码改动后决定是否安装。'));const b=el('button','查看候选版本并确认 →');b.onclick=()=>document.querySelector('.evolution')?.scrollIntoView({behavior:'smooth',block:'start'});c.append(b);inbox.append(c);}for(const item of home.attention){const c=el('article',null,'card inbox-card');c.dataset.state=item.task.state;c.append(badge(item.task.state),el('h3',item.task.title),el('p',item.message||item.task.goal));const b=el('button',item.task.state==='NEW'?'选择执行成员 →':item.task.state==='WAITING_REVIEW'?'查看交付并验收 →':item.task.state==='WAITING_INPUT'?'回复 Agent →':'看看如何继续 →');b.onclick=()=>item.task.state==='NEW'?(location.href='/tasks#'+encodeURIComponent(item.task.task_id)):action(()=>openDecision(item.task.task_id));c.append(b);inbox.append(c);}if(!home.attention.length&&!upgradeAttention){const e=el('div',null,'empty-state');e.append(el('span','✓','empty-icon'),el('strong',(counts.WAITING_AUTHORIZATION||0)?'请先处理上方执行授权':(counts.WAITING_ENVIRONMENT||0)?'有执行环境需要配置':'暂时不需要你介入'),el('span','新的提交、问题和授权申请会保存在这里。'));inbox.append(e);}if(workWaiting>home.attention.length)inbox.append(link('还有更多待处理工作 →','/tasks','small'));
 $('system-health').textContent=system.eligible_agents?'运行环境已就绪':system.connected_runtimes?'需要配置可用 Agent':'执行机器未连接';$('health-dot').classList.toggle('warning',!system.eligible_agents);$('system-hint').textContent=`${system.connected_runtimes} 台机器连接 · ${system.eligible_agents} 个配置可用的 Agent。模型是否可用以实际执行为准。`;$('connection').textContent=system.connected_runtimes+' 台在线机器';$('recent').replaceChildren();for(const t of home.recent){const a=link('','/tasks#'+t.task_id,'activity-item');a.append(el('strong',t.title),el('small',(WA.labels[t.state]||t.state)+' · '+date(t.updated_at_ms)));$('recent').append(a);}if(!home.recent.length)$('recent').append(el('p','工作开始后，进展会留在这里。','small muted'));}
const upgradeLabels={QUEUED:'等待构建',BUILDING:'隔离修改与测试中',READY:'候选版本待确认',WAITING_IDLE:'等待当前运行结束',INSTALLING:'安装并重启中',SUCCEEDED:'升级成功',ROLLED_BACK:'升级失败，已回滚',FAILED:'升级失败',CANCELLED:'已取消'};
function renderUpgrade(payload,system){
 const box=$('upgrade-card'),stage=$('upgrade-stage'),u=payload.upgrades?.[0],version=JSON.stringify([payload.enabled,u?.upgrade_id,u?.version,u?.candidate_sha256]);if(state.upgradeVersion===version)return;state.upgradeVersion=version;box.replaceChildren();stage.textContent=u?(upgradeLabels[u.state]||u.state):(payload.enabled?'已就绪':'未启用');
 if(!payload.enabled){box.append(el('p','当前启动方式没有升级守护进程。请使用项目的启动脚本运行。','small muted'));return;}
 if(!u){box.append(el('p','在聊天中明确说“给这个系统增加……”。确认需求后，AI 会在隔离副本中准备候选版本。','small muted'));return;}
 const card=el('article',null,'evolution-card');card.append(el('h3',u.title),el('p',upgradeLabels[u.state]||u.state,'upgrade-state'));
 if(u.summary)card.append(el('p',u.summary,'evolution-summary'));
 if(u.error)card.append(el('p',u.error,'evolution-error'));
 if(u.changes?.length){const details=el('details'),summary=el('summary',u.changes.length+' 个文件发生变化');const list=el('div',null,'change-list');for(const change of u.changes)list.append(el('code',change.path));details.append(summary,list);card.append(details);}
 if(u.patch){const details=el('details');details.append(el('summary','查看具体代码改动'),el('pre',u.patch));card.append(details);}
 if(u.candidate_sha256)card.append(el('p','候选版本 '+u.candidate_sha256.slice(0,12),'candidate-digest'));
 if(u.log){const details=el('details');details.append(el('summary','查看测试与构建记录'),el('pre',u.log));card.append(details);}
 if(u.state==='READY'){card.append(el('p','第二次确认后将暂停创建新运行，等待当前运行结束，备份数据并自动重启；健康检查失败会恢复旧版本。','upgrade-warning'));const actions=el('div',null,'upgrade-actions'),install=el('button','确认安装并重启','primary'),cancel=el('button','取消候选版本');install.onclick=()=>action(async()=>{const updated=await api('/upgrades/'+u.upgrade_id+'/install','POST',{expected_version:u.version,candidate_sha256:u.candidate_sha256});renderUpgrade({enabled:true,upgrades:[updated]},system);notice('已确认安装。系统会先等待正在执行的工作结束，再备份并重启。');});cancel.onclick=()=>action(async()=>{await api('/upgrades/'+u.upgrade_id+'/cancel','POST',{expected_version:u.version});await refreshOverview();});actions.append(install,cancel);card.append(actions);}
 else if(['QUEUED','BUILDING','WAITING_IDLE'].includes(u.state)){const actions=el('div',null,'upgrade-actions'),cancel=el('button','取消升级');cancel.onclick=()=>action(async()=>{await api('/upgrades/'+u.upgrade_id+'/cancel','POST',{expected_version:u.version});await refreshOverview();});actions.append(cancel);card.append(actions);}
 box.append(card);
}
function renderProtection(system){const p=system.data_protection,last=Date.parse(p?.last_success),stale=!Number.isFinite(last)||last<=0||Date.now()-last>(p?.interval_seconds||300)*2000,warning=!p?.enabled?'自动备份未启用':p.last_error?'自动备份失败':stale?'备份恢复点已过期':'';let n=$('data-protection-alert');if(!n){n=el('p',null,'scope-note');n.id='data-protection-alert';$('system-hint').after(n);}n.hidden=!warning;n.replaceChildren();if(warning)n.append(el('span',warning+'。'),link('查看数据保护 →','/system'));}
function renderImprovementProtection(payload){const issues=payload?.overview?.needs_attention||[];let n=$('improvement-alert');if(!n){n=el('p',null,'scope-note');n.id='improvement-alert';$('system-hint').after(n);}n.hidden=!issues.length;n.replaceChildren();if(issues.length)n.append(el('span',issues.join('；')+'。'),link('查看持续改进 →','/improvements'));}
async function refreshOverview(){const [home,system,upgrades,systemAgents,members,improvements]=await Promise.all([api('/home'),api('/system'),api('/upgrades'),api('/system/agents'),api('/agents'),api('/improvements/overview')]);state.homeBinding=systemAgents.bindings.find(b=>b.slot==='home_chat');state.members=members.agents;renderHomeExecutor();renderOverview(home,system,upgrades);renderUpgrade(upgrades,system);renderProtection(system);renderImprovementProtection(improvements);}
function renderHomeExecutor(){
 let box=$('home-executor');if(!box){box=el('div',null,'home-executor');box.id='home-executor';document.querySelector('.chat-history').before(box);}
 box.replaceChildren();const session=state.chat?.session,b=state.homeBinding,member=state.members?.find(a=>a.agent_id===(session?.agent_id||b?.agent_id));
 const info=el('div');info.append(el('span',session?'当前聊天成员：'+(member?.name||session.agent_id):'新对话成员：'+(member?.name||(b?'自动选择':'读取配置中…')),'small'));
 if(session)info.append(el('span',session.runtime_id+' · '+session.adapter_id+' · '+(session.model_id||'默认模型'),'small muted'));
 else if(member)info.append(el('span',member.runtime_id+' · '+member.adapter_id+' · '+(member.model_id||'默认模型'),'small muted'));
 box.append(info,link('配置系统岗位 →','/members#system-agents','small'));
 if(session){const button=el('button','使用当前配置接手');button.id='switch-chat-executor';button.type='button';button.disabled=state.busy||state.chat.state==='GENERATING'||!b;button.onclick=()=>{if(!confirm('确认按当前首页聊天岗位配置接手？将创建新的 Session，传递最近 12 条可见对话（长消息截断）。旧记录保留，未确认的旧建议失效。'))return;action(async()=>{setChat(await api('/home/chats/'+state.chat.chat_id+'/executor','POST',{expected_version:state.chat.version,binding_version:b.version}));notice('聊天执行者已切换。旧记录保留，发送下一条消息后在新 Session 中继续。');});};box.append(button);}
}
async function refresh(){if(state.loading)return;state.loading=true;try{await refreshOverview();state.chats=(await api('/home/chats')).chats;const current=state.chat?.chat_id||'';if(state.first){const wanted=location.hash.slice(1);const chosen=state.chats.find(c=>c.chat_id===wanted)||state.chats[0];if(chosen)setChat(await api('/home/chats/'+chosen.chat_id));state.first=false;}else if(current){const c=await api('/home/chats/'+current);if(!state.busy&&state.chat?.chat_id===current)setChat(c);}const select=$('chat-select');select.replaceChildren();const blank=el('option','新的对话');blank.value='';select.append(blank);for(const c of state.chats){const o=el('option',c.title+' · '+date(c.updated_at_ms));o.value=c.chat_id;select.append(o);}select.value=state.chat?.chat_id||'';renderThread();}finally{state.loading=false;controls();}}
$('home-message').oninput=()=>state.sendKey='';
$('chat-form').onsubmit=e=>{e.preventDefault();action(async()=>{const message=$('home-message').value.trim();if(!message)throw Error('先写下你想聊的事。');if(!state.chat){setChat(await api('/home/chats','POST',{idempotency_key:state.createKey}));history.replaceState(null,'','#'+state.chat.chat_id);}if(!state.sendKey)state.sendKey=key();setChat(await api('/home/chats/'+state.chat.chat_id+'/messages','POST',{message,expected_version:state.chat.version,idempotency_key:state.sendKey}));state.sendKey='';$('home-message').value='';});};
$('stop-chat').onclick=()=>action(async()=>{await api('/home/chats/'+state.chat.chat_id+'/stop','POST',{});notice('已请求停止回答，正在等待执行端确认。');});
$('new-chat').onclick=()=>{if($('home-message').value&&!confirm('放弃尚未发送的消息，开始新对话？'))return;state.first=false;state.sendKey='';state.createKey=key();$('home-message').value='';$('chat-select').value='';history.replaceState(null,'','/');setChat(null);$('home-message').focus();};
$('chat-select').onchange=()=>action(async()=>{if($('home-message').value&&!confirm('放弃尚未发送的消息，切换对话？')){$('chat-select').value=state.chat?.chat_id||'';return;}const chatID=$('chat-select').value;$('home-message').value='';state.sendKey='';state.createKey=key();setChat(chatID?await api('/home/chats/'+chatID):null);history.replaceState(null,'',chatID?'#'+chatID:'/');});
$('connect').onclick=()=>action(async()=>{WA.saveToken($('token').value);await refresh();notice('已连接，Token 仅保留在此标签页会话中。');});
async function openDecision(taskID){const result=await api('/work/tasks/'+taskID),review=result.work.reviews.find(r=>r.state==='PENDING');state.decision={taskID,result,review};state.replyKey=key();const t=result.detail.task,done=t.state==='COMPLETED';$('decision-title').textContent=t.title;$('decision-kind').textContent=WA.labels[t.state]||t.state;$('decision-version').textContent=review?'验收单 '+review.review_id:'回复会交给该工作的原 Agent 与 Session';$('decision-message').textContent=[...result.work.messages].reverse().find(m=>m.speaker!=='user')?.content||t.goal;$('decision-comment').value='';$('decision-error').hidden=true;$('decision-link').href='/tasks#'+taskID;$('decision-approve').hidden=!review;$('decision-reject').hidden=!review;$('decision-reply').hidden=!!review||done;$('decision-label').hidden=done;$('decision-hint').textContent=review?'只验收这次提交的以下文件版本。要求修改时请填写具体意见。':done?'工作已完成，可在完整记录中回看交付物和验收过程。':'发送后继续原来的工作。若你需要立即打断，请进入完整工作记录。';const artifacts=review?result.work.artifacts.filter(a=>review.artifact_ids.includes(a.artifact_id)):result.work.artifacts;state.decision.artifacts=artifacts;$('decision-artifact').replaceChildren();for(const a of artifacts){const o=el('option',a.name+' · v'+a.version);o.value=a.artifact_id;$('decision-artifact').append(o);}$('decision-files').hidden=!artifacts.length;$('decision-download').hidden=!artifacts.length;previewDecision();if(!$('decision-dialog').open)$('decision-dialog').showModal();}
const decisionChatBox=el('section');decisionChatBox.id='decision-review-chat';$('decision-label').before(decisionChatBox);const decisionChat=WAReviewChat.mount(decisionChatBox,{changed:refreshDecision,busyChanged:controls});
async function refreshDecision(){const d=state.decision;if(!d||!$('decision-dialog').open)return;const result=await api('/work/tasks/'+d.taskID);if(state.decision!==d||!$('decision-dialog').open)return;d.result=result;if(d.review)d.review=result.work.reviews.find(r=>r.review_id===d.review.review_id);decisionChat.update({...result,agents:state.members},d.review?.review_id);if(d.review&&d.review.state!=='PENDING')$('decision-hint').textContent='本次验收已结束或失效，不能再审批。旧文件与沟通记录保留，请重新打开最新提交。';controls();}
function previewDecision(){if(state.decision){const plan=state.decision.review?.kind==='plan',d=state.decision.result.work.development;$('decision-approve').textContent=plan?'批准方案，开始开发':'验收通过';if(plan){$('decision-kind').textContent='等待方案确认';$('decision-hint').textContent='独立 Agent 已评审。批准仅授权按当前方案开发，不代表最终验收。仓库：'+(d?.repository||'')+' · '+(d?.base_branch||'')+'；方案 hash：'+(d?.plan_hash||'');}}const a=state.decision?.artifacts.find(a=>a.artifact_id===$('decision-artifact').value);$('decision-preview').textContent=a?.content||'';if(state.decision){decisionChat.update({...state.decision.result,agents:state.members},state.decision.review?.review_id);controls();}}
$('decision-artifact').onchange=previewDecision;function closeDecision(){if((decisionChat.hasDraft()||$('decision-comment').value)&&!confirm('放弃尚未发送的问题或验收意见，关闭窗口？'))return;decisionChat.reset();$('decision-dialog').close();}$('close-decision').onclick=closeDecision;$('decision-dialog').addEventListener('cancel',e=>{e.preventDefault();closeDecision();});
async function decideReview(decision){if(decisionChat.hasDraft()||decisionChat.isBusy()||decisionChat.isWaiting())throw Error('请先完成验收沟通并处理未发送的问题，再作决定。');if(decision==='CHANGES_REQUESTED'&&!$('decision-comment').value.trim())throw Error('要求修改时，请先填写具体意见。');const d=state.decision;if(decision==='APPROVED'&&d.review.kind==='plan')decision='PLAN_APPROVED';await api('/work/tasks/'+d.taskID+'/reviews/'+d.review.review_id,'POST',{decision,comment:$('decision-comment').value,expected_discussion_version:d.review.discussion_version||0});decisionChat.reset();$('decision-dialog').close();await refreshOverview();notice(decision==='PLAN_APPROVED'?'方案已批准，原 Agent 将开始开发。':decision==='APPROVED'?'本次提交已验收通过，工作完成。':'修改意见已保存，原 Agent 会继续处理。');}
$('decision-approve').onclick=()=>action(()=>decideReview('APPROVED'));$('decision-reject').onclick=()=>action(()=>decideReview('CHANGES_REQUESTED'));
$('decision-reply').onclick=()=>action(async()=>{const message=$('decision-comment').value.trim();if(!message)throw Error('请写下回复或下一步要求。');await api('/work/tasks/'+state.decision.taskID+'/messages','POST',{message,idempotency_key:state.replyKey});$('decision-dialog').close();await refreshOverview();notice('回复已保存，将沿用原 Session 继续。');});
$('decision-comment').oninput=()=>state.replyKey=key();
$('decision-download').onclick=()=>action(async()=>{const a=state.decision.artifacts.find(a=>a.artifact_id===$('decision-artifact').value);if(a)await WA.download('/work/tasks/'+state.decision.taskID+'/artifacts/'+a.artifact_id,a.name);});
window.addEventListener('beforeunload',e=>{if($('home-message').value||$('decision-dialog').open&&($('decision-comment').value||decisionChat.hasDraft())){e.preventDefault();e.returnValue='';}});
async function poll(){if(!state.busy&&!decisionChat.isBusy()&&!document.hidden){try{await refresh();await refreshDecision();if(state.connectionLost){state.connectionLost=false;notice('系统已重新连接。');}}catch(e){state.connectionLost=true;notice(e.message+'，正在等待重新连接。',true);}}setTimeout(poll,2500);}
action(refresh);setTimeout(poll,2500);
