'use strict';
const {el,api,notice,date,key}=WA,$=id=>document.getElementById(id);let state={busy:false,candidates:[],target:null};
const fmt=n=>n==null?'未完整采集':Number(n).toLocaleString('zh-CN'),metric=(name,value)=>{const n=el('div',null,'metric-card');n.append(el('strong',value),el('span',name));return n;};
async function refresh(){
  const [overview,candidates,experiences,policies]=await Promise.all([
    api('/improvements/overview'),api('/improvements/candidates'),api('/improvements/experiences'),api('/improvements/policies')
  ]);
  const o=overview.overview,hours=o.median_cycle_time_ms==null?'—':(o.median_cycle_time_ms/3600000).toFixed(1)+' h';
  $('metrics').replaceChildren(
    metric('成熟样本',fmt(o.mature_evaluations)),metric('平均质量',Number(o.average_quality||0).toFixed(1)),
    metric('周期中位数',hours),metric('人工介入中位数',fmt(o.median_human_interventions)),
    metric('业务 Token',fmt(o.business_tokens)),metric('毛节省',fmt(o.gross_token_saving)),
    metric('改进开销',fmt(o.improvement_tokens)),metric('净收益',fmt(o.net_token_saving)),
    metric('运行中实验',fmt(o.active_experiments)),metric('待处理候选',fmt(o.pending_candidates)),metric('有效经验',fmt(o.experience_count))
  );
  $('readiness').textContent=`观测 ${o.readiness.observation_hours.toFixed(1)} 小时 · 数据覆盖 ${o.readiness.data_coverage.toFixed(1)}% · ${o.readiness.reason}`;
  renderExperiments(overview.experiments||[]);state.candidates=candidates.candidates||[];renderCandidates();
  renderExperiences(experiences.experiences||[]);renderPolicies(policies.policies||[]);
  $('connection').textContent=o.needs_attention?.length?o.needs_attention.join('；'):'改进系统正常';
}
function renderExperiments(items){$('experiments').replaceChildren();for(const x of items){const tr=el('tr');tr.append(el('td',x.candidate_id),el('td',x.state),el('td',`${x.baseline_samples} / ${x.candidate_samples}${x.promoted_samples?' / '+x.promoted_samples:''}`),el('td',String(x.score?.composite??0)),el('td',x.decision_reason||'观察中'));$('experiments').append(tr);}if(!items.length){const tr=el('tr'),td=el('td','暂无实验；首个实验须先满足 24 小时和 80% 数据覆盖门槛。','muted');td.colSpan=5;tr.append(td);$('experiments').append(tr);}}
function scope(x){return [x.repository,x.task_type,x.role_id,x.runtime_os].filter(Boolean).join(' · ')||'未限定';}
const lockable={prompt:['role_id','stage','overlay'],routing:['load_weight','success_weight','cost_weight'],recovery:['continuous_run','backoff_ms','split_environment_after'],test:['risk_mode','reviewer_count','retest_mode'],workflow:['require_agent_plan_review','require_human_plan_review','require_pr_review','require_passing_tests','require_human_acceptance','plan_review_round_limit']};
function actions(target,items){const wrap=el('div',null,'improvement-actions');for(const [name,label] of items){const b=el('button',label);b.onclick=()=>openAction(target,name,label);wrap.append(b);}return wrap;}
function renderCandidates(){$('candidates').replaceChildren();for(const x of state.candidates){const row=el('article',null,'improvement-row'),about=el('div');about.append(el('h3',x.title),el('p',x.rationale,'small muted'));row.append(about,el('span',x.type),el('span',x.state),actions({kind:'candidate',item:x},candidateActions(x)));const d=el('details');d.append(el('summary',`范围与配置差异 · ${scope(x.scope)}`),el('pre',JSON.stringify({scope:x.scope,patch:x.patch,evidence:x.evidence,locked_fields:x.locked_fields||[],validation_error:x.validation_error},null,2)));row.append(d);$('candidates').append(row);}if(!state.candidates.length)$('candidates').append(el('p','还没有改进候选。任务完成或持续受阻后会在后台生成分析。','empty-state'));}
function candidateActions(x){if(x.locked_fields?.length)return[['unlock_fields','解除字段锁定']];const lock=x.type==='experience'?[]:[['reject_and_lock','拒绝并锁定字段']];if(x.state==='VALIDATED')return[['start','开始灰度'],['reject','拒绝'],...lock];if(x.state==='CANARY')return[['promote','推广'],['pause','暂停'],['reject','拒绝'],...lock];if(x.state==='PAUSED')return[['start','继续灰度'],['reject','拒绝'],...lock];if(x.state==='PROMOTED')return[['rollback','回滚']];return[];}
function renderExperiences(items){$('experiences').replaceChildren();for(const x of items){const row=el('article',null,'improvement-row'),about=el('div');about.append(el('h3',x.situation),el('p',x.recommended_action,'small muted'));const available=x.state==='ACTIVE'?[['pause','暂停'],['retire','停用']]:x.state==='PAUSED'?[['activate','启用'],['retire','停用']]:x.state==='RETIRED'?[['activate','启用']]:[];row.append(about,el('span',`rev ${x.revision} · gen ${x.generation}`),el('span',x.state),actions({kind:'experience',item:x},available));const d=el('details');d.append(el('summary',`验证与实际效果 · ${scope(x.scope)}`),el('pre',JSON.stringify({avoid:x.avoid,verification:x.verification,evidence:x.evidence,samples:x.sample_count,effect:x.effect_score},null,2)));row.append(d);$('experiences').append(row);}if(!items.length)$('experiences').append(el('p','暂无已验证经验。','empty-state'));}
function renderPolicies(items){$('policies').replaceChildren();for(const x of items){const row=el('article',null,'improvement-row'),about=el('div');about.append(el('h3',`${x.policy_id} @ ${x.version}`),el('p',scope(x.scope),'small muted'));row.append(about,el('span',date(x.created_at_ms)),el('span',x.state),el('span','只读'));const d=el('details');d.append(el('summary','查看预定义策略与推广/回滚历史'),el('pre',JSON.stringify({prompt:x.prompt_policy,routing:x.routing_policy,recovery:x.recovery_policy,test:x.test_policy,workflow:x.workflow_policy,history:x.history||[]},null,2)));row.append(d);$('policies').append(row);}}
function openAction(target,action,label){state.target=target;$('action-title').textContent=target.kind==='candidate'?'处理改进候选':'处理经验';$('action-name').replaceChildren();const option=el('option',label||action);option.value=action;$('action-name').append(option);const showLocks=target.kind==='candidate'&&action==='reject_and_lock';$('action-lock-label').hidden=!showLocks;$('action-lock-fields').value='';$('action-lock-fields').placeholder=showLocks?`可选：${(lockable[target.item.type]||[]).join(', ')}`:'';$('action-reason').value='';$('action-error').hidden=true;$('action-dialog').showModal();}
$('action-form').onsubmit=e=>{e.preventDefault();if(state.busy)return;state.busy=true;const t=state.target,path=t.kind==='candidate'?`/improvements/candidates/${t.item.candidate_id}/actions`:`/improvements/experiences/${t.item.experience_id}/actions`,locked=$('action-lock-fields').value.split(/[,，\s]+/).map(x=>x.trim()).filter(Boolean);api(path,'POST',{action:$('action-name').value,reason:$('action-reason').value,expected_version:t.item.version,idempotency_key:key(),locked_fields:locked}).then(()=>{$('action-dialog').close();return refresh();}).catch(err=>{$('action-error').textContent=err.message;$('action-error').hidden=false;}).finally(()=>state.busy=false);};$('close-action').onclick=()=>$('action-dialog').close();$('refresh').onclick=()=>refresh().catch(e=>notice(e.message,true));$('connect').onclick=()=>{WA.saveToken($('token').value);refresh().catch(e=>notice(e.message,true));};refresh().catch(e=>notice(e.message,true));setInterval(()=>{if(!document.hidden&&!state.busy)refresh().catch(()=>{});},10000);
