'use strict';
const {el,api,notice,link,date}=WA,$=id=>document.getElementById(id),page=document.body.dataset.page;
const state={busy:false,loading:false,projects:[],project:null};
async function action(fn){if(state.busy)return;state.busy=true;notice('');document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message,true);if($('project-dialog')?.open){$('project-error').textContent=e.message;$('project-error').hidden=false;}}finally{state.busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
const row=(name,value)=>{const n=el('div',null,'status-row');n.append(el('span',name),el('strong',value));return n;};
async function refresh(){if(state.loading)return;state.loading=true;try{if(page==='system'){const [s,runtimes,home]=await Promise.all([api('/system'),api('/runtimes'),api('/home')]);$('connection').textContent=s.connected_runtimes+' 台在线机器';$('system-summary').replaceChildren(row('数据库',s.database==='ready'?'已就绪 · SQLite':'未就绪'),row('工作调度','自动调度已启用'),row('系统进化',s.upgrade_enabled?(s.maintenance_upgrade_id?'正在排空运行并升级':'升级守护进程已启用'):'未启用'),row('候选验证',s.upgrade_validation_sandbox||'不可用'),row('在线机器',String(s.connected_runtimes)),row('配置可用 Agent',String(s.eligible_agents)),row('排队中的工作',String(home.counts.QUEUED||0)),row('进行中的工作',String(home.counts.IN_PROGRESS||0)));$('runtime-list').replaceChildren();for(const rt of runtimes.runtimes){const c=el('article',null,'card');const connected=s.runtimes.some(r=>r.runtime_id===rt.runtime_id);c.append(el('h3',rt.runtime_id),row('连接',connected?'在线':'离线'),row('最近心跳',rt.last_seen_at_ms?date(rt.last_seen_at_ms):'尚未收到'));const d=el('details');d.append(el('summary','适配器与能力信息'),el('pre',JSON.stringify(rt.capabilities,null,2)));c.append(d);$('runtime-list').append(c);}if(!runtimes.runtimes.length)$('runtime-list').append(el('p','还没有登记执行机器。请启动本机工作助手或接入 Runtime。','empty-state'));$('agent-list').replaceChildren();for(const a of s.agents){const c=el('article',null,'card');c.append(el('h3',a.name),row('角色',a.role.name+' · v'+a.role.version),row('状态',a.state==='ACTIVE'?'启用':'停用'),row('当前容量',`${a.active_runs} / ${a.max_concurrent}`),row('模型',a.model_id||'运行环境默认'),row('执行机器',a.runtime_id),link('修改配置 →','/members#'+a.role_id,'small'));$('agent-list').append(c);}if(!s.agents.length)$('agent-list').append(link('还没有 Agent，前往成员管理页配置 →','/members','empty-state'));$('updated-at').textContent='最近读取：'+new Date().toLocaleTimeString()+' · 运行状态自动刷新；工作计数覆盖最近 500 件工作。';}else{state.projects=(await api('/projects')).projects;renderProjects();const s=await api('/system');$('connection').textContent=s.connected_runtimes+' 台在线机器';}}finally{state.loading=false;}}
function renderProjects(){const q=$('project-search').value.trim().toLowerCase(),projects=state.projects.filter(p=>(p.name+' '+p.context).toLowerCase().includes(q));$('project-count').textContent=`${projects.length} / ${state.projects.length} 份资料`;$('projects').replaceChildren();for(const p of projects){const c=el('article',null,'card');c.append(el('span','团队资料 · v'+p.version,'eyebrow'),el('h2',p.name),el('p',p.context.length>150?p.context.slice(0,150)+'…':p.context));const b=el('button','浏览资料 →');b.onclick=()=>showProject(p);c.append(b);$('projects').append(c);}if(!projects.length)$('projects').append(el('p',q?'没有匹配的团队资料。':'还没有团队资料。保存一份常用资料，创建工作时就能复用。','empty-state'));}
function showProject(p){state.project=p;$('project-error').hidden=true;$('project-title').textContent=p?p.name:'添加团队资料';$('project-form').hidden=!!p;$('project-view').hidden=!p;if(p){$('project-content').textContent=p.context;$('project-work-link').href='/tasks?project='+encodeURIComponent(p.project_id);}else{$('project-form').reset();}if(!$('project-dialog').open)$('project-dialog').showModal();}
$('connect').onclick=()=>action(async()=>{WA.saveToken($('token').value);await refresh();notice('已连接。');});
async function refreshProtection(){
 const p=await api('/admin/backups'),last=Date.parse(p.last_success),valid=Number.isFinite(last)&&last>0,stale=valid&&Date.now()-last>p.interval_seconds*2000;
 $('protection-status').replaceChildren(row('自动恢复点',!p.enabled?'未启用':p.running?'正在备份并校验':p.last_error||stale?'需要检查':'已启用'),row('备份间隔',p.enabled?`${p.interval_seconds/60} 分钟`:'—'),row('最近成功',valid?date(p.last_success):'尚无已验证恢复点'),row('校验方式','SHA-256 · SQLite 完整性'),row('保留策略','最近 48 份 + 30 天每日恢复点'));
 const warning=p.last_error||(!p.enabled?'自动备份未启用，请检查启动配置。':!valid?'还没有可用恢复点，请立即创建备份。':stale?'超过两个备份周期没有成功恢复点，请检查磁盘空间及写入权限。':'');
 $('protection-warning').hidden=!warning;$('protection-warning').textContent=warning;
 $('backup-directory').textContent=p.directory||'尚未配置';$('backup-history').replaceChildren();
 for(const b of p.snapshots||[]){const c=el('div',null,'card');c.append(el('strong',date(b.created_at)),el('p',`${b.reason==='manual'?'手动恢复点':b.reason==='startup'?'启动恢复点':'自动恢复点'} · ${b.files.map(f=>f.name).join(' + ')}`,'small muted'));$('backup-history').append(c);}
}
if(page==='system'){$('refresh').onclick=()=>action(async()=>{await refresh();await refreshProtection();});$('create-backup').onclick=()=>action(async()=>{await api('/admin/backups','POST',{});await refreshProtection();$('backup-result').textContent='恢复点已保存，校验通过。手动恢复点不会被自动清理。';});$('download-backup').onclick=()=>action(async()=>{await WA.download('/admin/backup','work-assistant-'+new Date().toISOString().replace(/[:.]/g,'-')+'.sqlite');$('backup-result').textContent='已于 '+new Date().toLocaleTimeString()+' 下载经校验的控制端数据库快照。';});}
else{$('project-search').oninput=renderProjects;$('new-project').onclick=()=>showProject(null);$('close-project').onclick=()=>$('project-dialog').close();$('copy-project').onclick=()=>{const p=state.project;showProject(null);$('project-name').value=p.name+'（副本）';$('project-context').value=p.context;};$('project-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('/projects','POST',{name:$('project-name').value,context:$('project-context').value});$('project-dialog').close();await refresh();notice('团队资料已保存，创建工作时可以选择它。');});};window.addEventListener('beforeunload',e=>{if($('project-dialog').open&&!$('project-form').hidden&&$('project-context').value){e.preventDefault();e.returnValue='';}});}
async function poll(){if(!state.busy&&!document.hidden&&!$('project-dialog')?.open){try{await refresh();if(page==='system')await refreshProtection();}catch(e){notice(e.message,true);}}setTimeout(poll,5000);}action(async()=>{await refresh();if(page==='system')await refreshProtection();});setTimeout(poll,5000);
