'use strict';
const $=id=>document.getElementById(id);
const state={token:WA.token(),tasks:[],roles:[],agents:[],projects:[],runtimes:[],current:null,id:'',busy:false,loading:false,artifactID:'',files:'',createKey:'',messageKey:''};
let activityRefresh=null;
const assignment=WAAssignment.mount($('assignment-panel'),{submit:(agentID,version)=>action(async()=>{try{await api('/work/tasks/'+state.id+'/assignment','POST',{agent_id:agentID,expected_version:version});assignment.reset();await selectTask(state.id);await list();notice(agentID?'分派已保存，等待指定成员执行。':'已请求自动分派，系统会选择合适的成员。');}catch(e){assignment.reset();await selectTask(state.id);throw e;}})});
const activity=WAActivity.mount($('activity-panel'),{onTaskEvent:()=>{if(!activityRefresh)activityRefresh=setTimeout(refreshFromEvent,400);}});
const reviewChatBox=WA.el('section');reviewChatBox.id='task-review-chat';$('composer').before(reviewChatBox);const reviewChat=WAReviewChat.mount(reviewChatBox,{changed:async()=>{if(state.id){await selectTask(state.id);await list();}},busyChanged:controls});
const labels={NEW:'待分派',QUEUED:'排队中',IN_PROGRESS:'进行中',WAITING_REVIEW:'待我验收',WAITING_INPUT:'待我回复',BLOCKED:'受阻',PAUSED:'已暂停',COMPLETED:'已完成',WAITING_SUBTASKS:'等待子任务'};
labels.ATTENTION='需要你';
const hierarchy=WATaskHierarchy.mount($('task-parents'),$('task-hierarchy'),{navigate:id=>action(()=>selectTask(id))});
function node(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
function executionLabel(config){return '推理：'+(config.reasoning_effort|| (config.reasoning_effort_source?'运行环境默认（具体值未报告）':'历史未记录'))+(config.execution_model_id&&config.execution_model_id!==config.model_id?' · 执行模型：'+config.execution_model_id:'');}
function duration(ms){if(!Number.isFinite(ms)||ms<1000)return'不足 1 秒';const seconds=Math.round(ms/1000);if(seconds<60)return seconds+' 秒';const minutes=ms/60000;if(minutes<60)return(minutes<10?minutes.toFixed(1):Math.round(minutes))+' 分钟';const hours=ms/3600000;if(hours<24)return(hours<10?hours.toFixed(1):Math.round(hours))+' 小时';const days=ms/86400000;return(days<10?days.toFixed(1):Math.round(days))+' 天';}
function summaryList(parent,title,items){if(!items?.length)return;parent.append(node('h3',title));const list=node('ul');for(const item of items)list.append(node('li',item));parent.append(list);}
function key(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';$('notice').hidden=!text;}
function headers(){return state.token?{Authorization:'Bearer '+state.token}:{};}
async function api(path,method='GET',body){const r=await fetch('/api/v1'+path,{method,headers:{...headers(),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(r.status===401?'请在连接设置中填写 API Token。':value.error||'请求失败');return value;}
async function action(fn){if(state.busy||state.loading||reviewChat.isBusy())return;state.busy=true;controls();notice('');try{await fn();}catch(e){notice(e.message,true);}finally{state.busy=false;controls();}}
function controls(){document.querySelectorAll('button').forEach(b=>b.disabled=state.busy||state.loading);reviewChat.controls(state.busy||state.loading);activity.controls();assignment.controls(state.busy||state.loading);if(!state.current)return;const done=state.current.detail.task.state==='COMPLETED',active=state.current.detail.runs.some(r=>['RUNNING','QUEUED'].includes(r.state)),pending=state.current.work.reviews.find(r=>r.state==='PENDING');$('composer').hidden=done||!!pending;$('pause').disabled=state.busy||state.loading||done||state.current.work.config.paused||state.current.detail.task.state==='NEW';$('steer').disabled=state.busy||state.loading||!active;$('download').disabled=state.busy||state.loading||!state.current.work.artifacts.length;const blocked=state.busy||state.loading||reviewChat.isBusy()||reviewChat.isWaiting()||reviewChat.hasDraft()||!pending;const testsBlocked=WATestPipelines.blocked(state.current.work.test_pipelines||[]);$('approve').disabled=blocked||testsBlocked;$('approve').title=testsBlocked?'最新 PR 版本的 QA 回归尚未通过，请查看回归测试记录':'';$('reject').disabled=blocked;}
function option(value,label){const o=node('option',label);o.value=value;return o;}
function options(select,items,field,label,empty){const old=select.value;select.replaceChildren(option('',empty));for(const item of items)select.append(option(item[field],label(item)));select.value=old;}
async function library(){const [roles,agents,projects,system]=await Promise.all([api('/roles'),api('/agents'),api('/projects'),api('/system')]);state.roles=roles.roles;state.agents=agents.agents;state.projects=projects.projects;state.runtimes=system.runtimes||[];options($('new-role'),state.roles,'role_id',r=>r.name+' · v'+r.version,'任意合适角色');updateCreationAgents();options($('new-project'),state.projects,'project_id',p=>p.name,'不附加团队资料');$('health').textContent=system.eligible_agents?`${system.connected_runtimes} 台在线 · ${system.eligible_agents} 个可用 Agent`:'未就绪：请在成员管理页配置在线 Agent';activity.update(state.current,state.agents,state.runtimes);assignment.update(state.current,state.agents,state.runtimes);}
function visibleTasks(){const q=$('search').value.trim().toLowerCase(),filter=$('filter').value;return state.tasks.filter(t=>WATaskHierarchy.matchesFilter(t,filter)&&(!q||(t.title+' '+t.goal).toLowerCase().includes(q)));}
function appendProgress(parent,t){const text=WATaskHierarchy.progressText(t);if(text){const hint=node('small',text,'work-subtasks');hint.dataset.attention=String(!!t.subtasks?.needs_attention);parent.append(hint);}}
function renderList(){const tasks=visibleTasks();$('task-list').replaceChildren();if(!tasks.length)$('task-list').append(node('p','没有符合条件的原始任务。','empty'));for(const t of tasks){const active=t.task_id===state.id||state.current?.hierarchy?.roots.some(r=>r.task_id===t.task_id);const b=node('button',null,'task-item'+(active?' active':''));b.append(node('strong',t.title),node('small',(labels[t.state]||t.state)+' · '+new Date(Math.max(t.updated_at_ms,t.subtasks?.updated_at_ms||0)).toLocaleString()));appendProgress(b,t);b.onclick=()=>action(()=>selectTask(t.task_id));$('task-list').append(b);}}
async function list(){state.tasks=(await api('/work/tasks?scope=roots')).tasks;renderList();renderWorkOverview();}
async function selectTask(id){
 const switching=state.id!==id;
 if(switching&&($('message').value||$('review-comment').value||reviewChat.hasDraft())&&!confirm('放弃尚未发送的消息或验收意见，切换任务？')){history.replaceState(null,'',state.id?'#'+state.id:'/tasks');return;}
 const [current,relations]=await Promise.all([api('/work/tasks/'+encodeURIComponent(id)+'?event_limit=30'),api('/work/tasks/'+encodeURIComponent(id)+'/hierarchy')]);
 if(switching){reviewChat.reset();state.artifactID='';state.messageKey='';$('message').value='';$('review-comment').value='';}
 current.hierarchy=relations;state.current=current;state.id=id;history.replaceState(null,'','#'+id);renderTask();renderList();
}
function renderTask(){const {detail,work}=state.current,t=detail.task,presentation=WATaskReferences.presentation(t,work);WATaskReferences.render($('task-references'),work.references);$('welcome').hidden=true;$('task').hidden=false;$('title').textContent=presentation.title;$('goal').textContent=presentation.goal;$('status').textContent=labels[t.state]||t.state;$('status').dataset.state=t.state;const owner=state.agents.find(a=>a.agent_id===t.assigned_agent_id);const preferred=state.agents.find(a=>a.agent_id===work.config.preferred_agent_id);$('owner').textContent=owner?owner.name+' · '+(detail.session?.model_id||'默认模型'):preferred?preferred.name+' · 等待执行':t.state==='NEW'?'待分派':'自动分派中';$('session').textContent=detail.session?JSON.stringify({task_id:t.task_id,agent_id:detail.session.agent_id,session_id:detail.session.session_id,native_session:detail.session.agent_session_ref,runtime:detail.session.runtime_id,role_version:detail.runs[0]?.role_snapshot?.version,team_material:work.config.project.name||'未附加团队资料',mode:'只读执行 · 本地产物'},null,2):'首次调度后建立 Session。';$('scheduler-error').hidden=!work.config.scheduler_error;$('scheduler-error').textContent='等待调度 / 需要处理：'+work.config.scheduler_error;
 const box=$('messages'),nearBottom=box.scrollTop+box.clientHeight>=box.scrollHeight-60;box.replaceChildren();for(const m of work.messages){const b=node('div',null,'bubble '+m.speaker);b.append(node('span',(m.speaker==='user'?'你':m.speaker==='assistant'?(owner?.name||'Agent'):'系统')+' · '+new Date(m.created_at_ms).toLocaleTimeString(),'speaker'),node('div',WATaskReferences.message(t,work,m)));if(m.delivery==='PENDING')b.append(node('div','已保存 · 等待下一轮处理','delivery'));box.append(b);}if(nearBottom)box.scrollTop=box.scrollHeight;
 const review=work.reviews.find(r=>r.state==='PENDING');if(review?.review_id&&review.review_id!==$('review').dataset.reviewId){state.artifactID=review.artifact_ids[0]||'';$('review-comment').value='';}$('review').hidden=!review;$('review').dataset.reviewId=review?.review_id||'';
 const dev=work.development,isPlan=review?.kind==='plan';
 $('approve').textContent=isPlan?'批准方案，开始开发':'验收通过';
 $('review-heading').textContent=isPlan?'方案待你确认':'本次提交待你验收';
 let phaseBox=$('development-phase');if(!phaseBox){phaseBox=node('section',null,'panel');phaseBox.id='development-phase';$('review').before(phaseBox);}
 phaseBox.hidden=!dev;phaseBox.replaceChildren();
 if(dev){const phase=dev.phase==='IMPLEMENTING'&&t.state==='WAITING_REVIEW'?'等待最终验收':({PLANNING:'形成 / 修订方案',AGENT_REVIEW:'Agent 方案互审',HUMAN_REVIEW:'等待你确认方案',IMPLEMENTING:'开发 / PR 反馈处理'}[dev.phase]||dev.phase);
 phaseBox.append(node('h3',phase),node('p','方案 → Agent 互审 → 你确认 → 开发与验证 → PR 评审 → 最终验收','small muted'));
 if(dev.repository)phaseBox.append(node('p','待审批 / 已批准范围：'+dev.repository+' · '+dev.base_branch,'small'));
 if(dev.plan_hash)phaseBox.append(node('p','方案版本 '+dev.version+' · SHA-256 '+dev.plan_hash,'small'));
 if(dev.reviewer_task_id){const a=node('a','查看方案 reviewer 的工作与讨论');a.href='/tasks#'+dev.reviewer_task_id;phaseBox.append(a);}
 }
 assignment.update(state.current,state.agents,state.runtimes);
 hierarchy.update(state.current,state.agents,state.roles);
 WATestPipelines.render($('test-pipelines'),work.test_pipelines||[],{resolve:p=>action(async()=>{if(!confirm('请先在 GitLab 按申请标识核查，确认没有创建对应流水线。重置后 Agent 可以申请重试；如果判断错误，可能重复运行测试。确认未创建？'))return;const result=await api('/work/tasks/'+encodeURIComponent(p.task_id)+'/test-pipelines/'+encodeURIComponent(p.request_id)+'/resolve','POST',{confirm_not_created:true});await selectTask(state.id);await list();notice(result.status==='recovered'?'已找回原 pipeline 并恢复轮询，没有重跑。':'核查确认已记录，原 Agent 可以分析后显式重试。');})});
 WATestPipelines.renderPublications($('publications'),work.publications||[],{resolve:p=>action(async()=>{if(!confirm('确认已在原页面检查，没有创建这条评论？系统会先再次核对；只有完整查询仍未找到时才允许重试。判断错误可能导致重复评论。'))return;const result=await api('/work/tasks/'+encodeURIComponent(p.task_id)+'/publications/'+encodeURIComponent(p.key)+'/resolve','POST',{confirm_not_created:true});await selectTask(state.id);notice(result.status==='recovered'?'已找回原评论，没有重复发布':result.message||result.status);})});
 $('send').textContent=t.state==='NEW'?'保存补充要求':'发送 / 继续';
 renderSummary(detail.summary,t);
 if(detail.summary?.executor)$('summary-body').append(node('p','最终交付执行配置 · '+executionLabel(detail.summary.executor),'small muted'));
 reviewChat.update({...state.current,agents:state.agents});
 activity.update(state.current,state.agents,state.runtimes);
 const old=state.artifactID,sel=$('artifact');sel.replaceChildren();for(const a of work.artifacts)sel.append(option(a.artifact_id,`${a.name} · v${a.version}${review?.artifact_ids.includes(a.artifact_id)?' · 本次验收':''}`));state.artifactID=work.artifacts.some(a=>a.artifact_id===old)?old:(work.artifacts[0]?.artifact_id||'');sel.value=state.artifactID;renderArtifact();
 $('runs').replaceChildren();for(const r of detail.runs.slice(-10).reverse())$('runs').append(node('p',`${r.run_id}\n${r.state} · ${r.adapter_id} · ${r.model_id||'默认模型'} · ${executionLabel(r)}${r.error?'\n'+r.error:''}`,'prewrap'));
 $('events').textContent=detail.events.slice(-30).map(e=>`${new Date(e.occurred_at_ms).toLocaleTimeString()} ${e.event_type}\n${e.payload.message||e.payload.error||''}`).join('\n');$('reviews').replaceChildren();for(const r of work.reviews){const row=node('details');row.append(node('summary',`${r.state} · ${r.review_id}`),node('p',r.comment||'没有正式验收意见','prewrap'));for(const turn of (work.review_turns||[]).filter(t=>t.review_id===r.review_id)){row.append(node('p','你：'+turn.question,'prewrap'));if(turn.answer)row.append(node('p','交付 Agent：'+turn.answer,'prewrap'));if(turn.error)row.append(node('p',turn.error,'small error'));} $('reviews').append(row);}controls();}
function renderSummary(summary,task){const body=$('summary-body');body.replaceChildren();if(!summary){$('summary-state').textContent='待生成';body.append(node('p',task.state==='COMPLETED'?'这件历史工作尚无总结。':'任务完成并验收通过后，系统会自动汇总结果、耗时、等待、返工和可复用经验。','summary-empty'));return;}$('summary-state').textContent=`v${summary.version} · ${WA.date(summary.completed_at_ms)}`;body.append(node('p',summary.result,'summary-result'));const m=summary.metrics,grid=node('div',null,'summary-metrics');for(const [label,value] of [['总周期',duration(m.cycle_time_ms)],['Agent 运行',duration(m.active_run_time_ms)],['排队等待',duration(m.queue_wait_ms+m.runtime_queue_wait_ms)],['等待验收',duration(m.human_review_wait_ms)]]){const card=node('div');card.append(node('strong',value),node('span',label));grid.append(card);}body.append(grid);const details=node('details',null,'summary-details');details.append(node('summary','展开效率明细'));const who=[summary.executor.role_name,summary.executor.agent_id,summary.executor.model_id].filter(Boolean).join(' · ');if(who)details.append(node('p','执行：'+who,'small muted'));details.append(node('p',`运行 ${m.run_count} 轮（失败 ${m.failed_run_count} / 中断 ${m.interrupted_run_count}） · 验收 ${m.review_round_count} 轮（打回 ${m.changes_requested_count}） · 补充/改向 ${m.guidance_message_count} 次 · 交付 ${m.deliverable_count} 个文件 / ${m.artifact_version_count} 个版本${m.subtask_count?` · 子任务 ${m.completed_subtask_count}/${m.subtask_count} 完成`:''}`,'small'));if(summary.acceptance_comment)details.append(node('p','最终验收意见：'+summary.acceptance_comment,'small prewrap'));summaryList(details,'可复用经验',summary.learnings);summaryList(details,'Agent 建议的改进',summary.improvements);if(summary.efficiency_signals?.length){details.append(node('h3','系统识别的效率信号'));const list=node('ul');for(const signal of summary.efficiency_signals){const item=node('li');item.append(node('strong',signal.evidence+'：'),document.createTextNode(signal.suggestion));list.append(item);}details.append(list);}if(summary.accepted_artifacts?.length)summaryList(details,'最终验收的交付物',summary.accepted_artifacts.map(a=>`${a.name} · v${a.version}`));body.append(details);}
function renderArtifact(){const a=state.current?.work.artifacts.find(a=>a.artifact_id===state.artifactID);$('preview').textContent=a?.content||'Agent 提交后，文件会出现在这里。';$('artifact-info').textContent=a?`v${a.version} · ${new Date(a.created_at_ms).toLocaleString()} · SHA-256 ${a.sha256}`:'';$('download').disabled=!a;}
async function download(path,filename){const r=await fetch('/api/v1'+path,{headers:headers()});if(!r.ok)throw Error('下载失败：'+r.status);const url=URL.createObjectURL(await r.blob()),a=node('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function createDialog(){state.createKey=key();updateCreationMode(); $('create-dialog').showModal();$('new-title').focus();}
$('new').onclick=createDialog;$('welcome-new').onclick=createDialog;$('close-dialog').onclick=()=>$('create-dialog').close();
$('search').oninput=()=>{renderList();renderWorkOverview();};$('filter').onchange=()=>{renderList();renderWorkOverview();};$('artifact').onchange=()=>{state.artifactID=$('artifact').value;renderArtifact();};
function updateCreationAgents(){const select=$('new-agent'),old=select.value;select.replaceChildren(option('','选择执行成员'));const requirements={role_id:$('new-role').value,capabilities:$('new-capabilities').value.split(',').map(c=>c.trim()).filter(Boolean)};for(const item of WAAssignment.candidates(requirements,state.agents,state.runtimes)){const o=option(item.value,item.label);o.disabled=item.disabled;select.append(o);}select.value=[...select.options].some(o=>o.value===old)?old:'';}
function updateCreationMode(){const mode=$('new-assignment-mode').value;$('new-agent-label').hidden=mode!=='member';$('new-agent').required=mode==='member';$('new-agent').disabled=mode!=='member';$('create').textContent=mode==='later'?'创建任务 →':mode==='member'?'创建并交给指定成员 →':'创建并自动分派 →';$('new-assignment-note').textContent=mode==='later'?'先保存任务，创建后在“执行安排”中选择成员或自动分派。':mode==='member'?'指定成员忙碌或离线时留在队列等待，不自动换人。':'由当前路由配置按角色、能力、在线状态和容量选择；没有合适成员时等待。';updateCreationAgents();}
$('new-role').onchange=updateCreationAgents;$('new-capabilities').oninput=updateCreationAgents;$('new-assignment-mode').onchange=updateCreationMode;
$('attachments').onchange=async()=>{try{const files=[...$('attachments').files];if(files.reduce((sum,f)=>sum+f.size,0)>24000)throw Error('附件总计最多 24 KB。');const parts=[];for(const f of files){const content=await f.text();if(content.includes('\u0000'))throw Error('只支持 UTF-8 文本文件。');parts.push(`附件 ${f.name}:\n${content}`);}state.files=parts.length?'\n\n'+parts.join('\n\n'):'';$('attachment-info').textContent=files.map(f=>f.name).join('、');}catch(e){state.files='';$('attachments').value='';$('attachment-info').textContent='';notice(e.message,true);}};
$('create-form').onsubmit=e=>{e.preventDefault();action(async()=>{const mode=$('new-assignment-mode').value;const t=await api('/work/tasks','POST',{title:$('new-title').value,goal:$('new-goal').value+state.files,requirements:{role_id:$('new-role').value,capabilities:$('new-capabilities').value.split(',').map(x=>x.trim()).filter(Boolean)},defer_assignment:mode==='later',agent_id:mode==='member'?$('new-agent').value:'',project_id:$('new-project').value,idempotency_key:state.createKey});$('create-dialog').close();$('create-form').reset();updateCreationMode();state.files='';$('attachment-info').textContent='';$('message').value='';$('review-comment').value='';state.artifactID='';await list();await selectTask(t.task_id);notice(mode==='later'?'任务已保存，请在“执行安排”中指定成员或自动分派。':mode==='member'?'任务已保存，等待指定成员执行。':'任务已保存，正在自动分派。');});};
$('save-project').onclick=()=>action(async()=>{const p=await api('/projects','POST',{name:$('project-name').value,context:$('project-context').value});await library();$('new-project').value=p.project_id;$('project-name').value='';$('project-context').value='';notice('团队资料已保存。');});
function send(interrupt){action(async()=>{const message=$('message').value.trim();if(!message)throw Error('请先填写下一步要求。');if(!state.messageKey)state.messageKey=key();await api('/work/tasks/'+state.id+'/messages','POST',{message,interrupt,idempotency_key:state.messageKey});state.messageKey='';$('message').value='';$('review-comment').value='';await selectTask(state.id);await list();notice(state.current.detail.task.state==='NEW'?'补充要求已保存；选择执行安排后再开始工作。':interrupt?'要求已保存，正在请求中断；随后沿用原 Session 继续。':'消息已保存，将在下一轮交给原 Agent。');});}
$('message').oninput=()=>{state.messageKey='';};$('send').onclick=()=>send(false);$('steer').onclick=()=>send(true);
$('pause').onclick=()=>action(async()=>{await api('/work/tasks/'+state.id+'/pause','POST',{});await selectTask(state.id);await list();});
function review(decision){action(async()=>{if(reviewChat.hasDraft()||reviewChat.isWaiting())throw Error('请先完成验收沟通并处理未发送的问题。');const reviewID=$('review').dataset.reviewId,r=state.current.work.reviews.find(r=>r.review_id===reviewID);if(decision==='APPROVED'&&r.kind==='plan')decision='PLAN_APPROVED';await api('/work/tasks/'+state.id+'/reviews/'+reviewID,'POST',{decision,comment:$('review-comment').value,expected_discussion_version:r.discussion_version||0});$('review-comment').value='';await selectTask(state.id);await list();notice(decision==='PLAN_APPROVED'?'方案已批准，原 Agent 将开始隔离开发。':decision==='APPROVED'?'已验收，任务完成并已生成总结。':'修改意见已保存，将回到原 Agent / Session。');});}
$('approve').onclick=()=>review('APPROVED');$('reject').onclick=()=>review('CHANGES_REQUESTED');
$('download').onclick=()=>action(async()=>{const a=state.current.work.artifacts.find(a=>a.artifact_id===state.artifactID);if(a)await download('/work/tasks/'+state.id+'/artifacts/'+a.artifact_id,a.name);});
$('backup').onclick=()=>action(async()=>{await download('/admin/backup','work-assistant-'+new Date().toISOString().replace(/[:.]/g,'-')+'.sqlite');notice('备份包含任务、总结、对话、角色版本、团队资料、产物和验收记录；不包含各机器的原生 Agent Session 文件或仓库。');});
$('connect').onclick=()=>action(async()=>{WA.saveToken($('token').value);state.token=WA.token();await library();await list();if(state.id){await selectTask(state.id);activity.reconnect();}notice('已连接，Token 仅保存在此标签页会话中，页面切换时仍可使用。');});
window.addEventListener('beforeunload',e=>{if($('message').value||$('review-comment').value||reviewChat.hasDraft()){e.preventDefault();e.returnValue='';}});
async function refreshFromEvent(){activityRefresh=null;if(!state.id)return;if(state.busy||state.loading||reviewChat.isBusy()||$('create-dialog').open){activityRefresh=setTimeout(refreshFromEvent,500);return;}state.loading=true;try{await selectTask(state.id);await list();}catch(e){notice(e.message+'，稍后重试读取状态。',true);}finally{state.loading=false;controls();}}
async function poll(){if(!state.busy&&!state.loading&&!reviewChat.isBusy()&&!$('create-dialog').open){state.loading=true;try{await list();if(state.id){const relations=await api('/work/tasks/'+encodeURIComponent(state.id)+'/hierarchy');if(!activity.isConnected()||relations.task_version!==state.current?.detail.task.version)await selectTask(state.id);else state.current.hierarchy=relations;}await library();hierarchy.update(state.current,state.agents,state.roles);renderList();}catch(e){notice(e.message+'，稍后重试读取状态。',true);}finally{state.loading=false;controls();}}setTimeout(poll,5000);}
function renderWorkOverview(){
 const counts=$('work-counts');counts.replaceChildren();
 for(const [title,bucket] of [['等待队列','queued'],['推进中','active'],['需要你','attention'],['已完成','completed']]){const n=node('div');n.append(node('strong',state.tasks.filter(t=>WATaskHierarchy.bucket(t)===bucket).length),node('span',title));counts.append(n);}
 const q=$('search').value.trim(),f=$('filter').value,tasks=visibleTasks();
 $('work-list-count').textContent=tasks.length+' 件原始任务';$('work-list-heading').textContent=f==='QUEUED'?'等待队列':f?(labels[f]||f):q?'搜索结果':'全部工作';$('work-table').replaceChildren();
 for(const t of tasks){
  const b=node('button',null,'work-table-row'),title=node('div'),status=node('div',null,'work-task-status');
  title.append(node('strong',t.title),node('small',t.goal.length>65?t.goal.slice(0,65)+'…':t.goal));appendProgress(title,t);status.append(WA.badge(t.state));
  if(t.subtasks?.needs_attention)status.append(node('small','子任务需要你','hierarchy-attention'));
  b.append(title,status,node('span',state.agents.find(a=>a.agent_id===(t.assigned_agent_id||t.preferred_agent_id))?.name||(t.state==='NEW'?'待分派':'自动分派中'),'muted'),node('span',WA.date(Math.max(t.updated_at_ms,t.subtasks?.updated_at_ms||0)),'muted'));
  b.onclick=()=>action(()=>selectTask(t.task_id));$('work-table').append(b);
 }
 if(!tasks.length)$('work-table').append(node('p',q||f?'没有符合条件的原始任务。':'还没有工作。可以在首页与助理商量，也可以直接创建。','empty-state'));
}
$('back-to-list').onclick=()=>{if(($('message').value||reviewChat.hasDraft()||$('review-comment').value)&&!confirm('放弃尚未发送的消息或意见，返回工作列表？'))return;reviewChat.reset();state.current=null;state.id='';activity.update(null);assignment.update(null);clearTimeout(activityRefresh);activityRefresh=null;state.messageKey='';$('message').value='';$('review-comment').value='';$('task').hidden=true;$('welcome').hidden=false;history.replaceState(null,'','/tasks');renderList();renderWorkOverview();};
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(id&&id!==state.id)action(()=>selectTask(id));});
window.addEventListener('pagehide',()=>{clearTimeout(activityRefresh);activity.dispose();});
action(async()=>{await library();await list();const id=location.hash.slice(1);if(id)await selectTask(id);const project=new URLSearchParams(location.search).get('project');if(project&&state.projects.some(p=>p.project_id===project)){$('new-project').value=project;createDialog();}});setTimeout(poll,5000);
