'use strict';
const $=id=>document.getElementById(id);
const state={token:WA.token(),tasks:[],roles:[],agents:[],projects:[],runtimes:[],current:null,id:'',busy:false,loading:false,artifactID:'',files:'',createKey:'',messageKey:''};
let activityRefresh=null;
const assignment=WAAssignment.mount($('assignment-panel'),{submit:(agentID,version)=>action(async()=>{try{await api('/work/tasks/'+state.id+'/assignment','POST',{agent_id:agentID,expected_version:version});assignment.reset();await selectTask(state.id);await list();notice(agentID?'分派已保存，等待指定成员执行。':'已请求自动分派，系统会选择合适的成员。');}catch(e){assignment.reset();await selectTask(state.id);throw e;}})});
const activity=WAActivity.mount($('activity-panel'),{onTaskEvent:()=>{if(!activityRefresh)activityRefresh=setTimeout(refreshFromEvent,400);}});
const consultation=WATaskConsultation.mount($('consultation-dialog'));
const reviewChatBox=WA.el('section');reviewChatBox.id='task-review-chat';$('review-chat-slot').append(reviewChatBox);const reviewChat=WAReviewChat.mount(reviewChatBox,{changed:async()=>{if(state.id){await selectTask(state.id);await list();}},busyChanged:controls});
const taskPermissions=WAPermissions.mountTask($('task-permission-panel'),$('task-permission-requests'),{changed:async()=>{if(state.id){await selectTask(state.id);await list();}}});
const labels={NEW:'待分派',QUEUED:'排队中',IN_PROGRESS:'进行中',WAITING_REVIEW:'待我验收',WAITING_INPUT:'待我回复',BLOCKED:'受阻',PAUSED:'已暂停',COMPLETED:'已完成',WAITING_SUBTASKS:'等待子任务',WAITING_TESTS:'等待 CI'};
labels.ATTENTION='需要你';
Object.assign(labels,{WAITING_AUTHORIZATION:'等待授权',WAITING_ENVIRONMENT:'等待环境'});
const hierarchy=WATaskHierarchy.mount($('task-parents'),$('task-hierarchy'),{navigate:id=>action(()=>selectTask(id))});
function node(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
function markdown(text,cls='markdown-body'){return WA.markdown?WA.markdown(text,cls):node('div',text,cls);}
function resultOf(run){try{return JSON.parse(run?.output||'{}');}catch{return{};}}
function latestPlanChange(detail){for(const run of [...(detail.runs||[])].sort((a,b)=>b.created_at_ms-a.created_at_ms)){const result=resultOf(run);if(result.outcome==='replan'){const update=result.task_update||{};return{run,reason:update.reason||result.message||'实施范围发生重大变化，需要重新评审。',changes:update.approach||'请查看修订后的完整方案。',analysis:update.analysis||'',validation:update.validation||''};}}return null;}
function renderPlanChange(detail){const box=$('plan-change'),change=latestPlanChange(detail);box.hidden=!change;box.replaceChildren();if(!change)return;const head=node('div',null,'plan-change-head'),title=node('div');title.append(node('span','PLAN CHANGED','plan-change-kicker'),node('h2','实施中发现重大方案变化'));head.append(title,node('span',WA.date(change.run.finished_at_ms||change.run.created_at_ms),'plan-change-meta'));const grid=node('div',null,'plan-change-grid');for(const [titleText,content] of [['为什么要改',change.reason],['方案改了什么',change.changes]]){const item=node('section',null,'plan-change-item');item.append(node('h3',titleText),markdown(content));grid.append(item);}box.append(head,grid);const evidence=[change.analysis,change.validation].filter(Boolean).join('\n\n');if(evidence){const details=node('details',null,'plan-change-evidence');details.append(node('summary','查看触发证据和验证结果'),markdown(evidence));box.append(details);}}
function renderPendingInput(task,work){const panel=$('pending-input'),question=$('pending-input-question');panel.hidden=task.state!=='WAITING_INPUT';question.replaceChildren();if(panel.hidden)return;const prompt=[...(work.messages||[])].reverse().find(message=>message.speaker==='assistant')?.content||'Agent 没有提交可显示的问题。这是异常状态，请查看运行记录或直接告诉 Agent 下一步怎么处理。';question.append(markdown(prompt));}
function renderPendingReview(review,work){const panel=$('pending-review');panel.hidden=!review;if(!review)return;const plan=review.kind==='plan',artifact=(work.artifacts||[]).find(item=>(review.artifact_ids||[]).includes(item.artifact_id));$('pending-review-heading').textContent=plan?'方案待你确认':'交付结果待你验收';$('pending-review-summary').textContent=plan?`开发 Agent 与方案 Reviewer 已完成互审${artifact?'，最终方案为 '+artifact.name:''}。批准前不会开始开发。`:`Agent 已提交本轮结果${artifact?'：'+artifact.name:''}。请查看交付物和验收沟通后决定通过或打回。`;$('pending-review-open').textContent=plan?'查看方案并决定':'查看交付并验收';}
function renderValidationPlan(parent,plan){if(!plan)return;const details=node('details',null,'validation-plan');details.open=true;details.append(node('summary','验证策略 · PR 前门禁 '+plan.final_gate.length+' 项'));const intro=node('p','增量修改只验证受影响项；稳定候选再执行最终门禁。','small muted');details.append(intro);const labels={reuse:'复用已有证据',rerun:'受影响，必须重跑',add:'需要补测',exclude:'本次排除'};for(const key of ['reuse','rerun','add','exclude']){const items=plan[key]||[];if(!items.length)continue;const section=node('section',null,'validation-group');section.append(node('h4',labels[key]+' · '+items.length));const list=node('ul');for(const item of items){const row=node('li');row.append(node('strong',item.scenario),node('span',item.reason,'validation-reason'));if(item.evidence)row.append(node('small','依据：'+item.evidence,'muted'));list.append(row);}section.append(list);details.append(section);}const gate=node('section',null,'validation-group final-gate');gate.append(node('h4','稳定候选最终门禁'));const gateList=node('ol');for(const item of plan.final_gate)gateList.append(node('li',item));gate.append(gateList);details.append(gate);parent.append(details);}
function executionLabel(config){return '推理：'+(config.reasoning_effort|| (config.reasoning_effort_source?'运行环境默认（具体值未报告）':'历史未记录'))+(config.execution_model_id&&config.execution_model_id!==config.model_id?' · 执行模型：'+config.execution_model_id:'');}
function runStateLabel(value){return({QUEUED:'本轮排队中',RUNNING:'本轮执行中',COMPLETED:'本轮已结束',FAILED:'本轮执行失败',INTERRUPTED:'本轮已中断'}[value]||value);}
function duration(ms){if(!Number.isFinite(ms)||ms<1000)return'不足 1 秒';const seconds=Math.round(ms/1000);if(seconds<60)return seconds+' 秒';const minutes=ms/60000;if(minutes<60)return(minutes<10?minutes.toFixed(1):Math.round(minutes))+' 分钟';const hours=ms/3600000;if(hours<24)return(hours<10?hours.toFixed(1):Math.round(hours))+' 小时';const days=ms/86400000;return(days<10?days.toFixed(1):Math.round(days))+' 天';}
function taskElapsed(task,runs=[],summary=null,now=Date.now()){const starts=[Number(task?.first_run_at_ms||0),...(runs||[]).map(run=>Number(run.started_at_ms||0))].filter(value=>value>0),start=starts.length?Math.min(...starts):0;if(!start)return'';if(task.state==='COMPLETED'){const end=Number(summary?.completed_at_ms||task.completed_at_ms||task.updated_at_ms||0);return end>=start?'运行了 '+duration(end-start):'';}return now>=start?'已运行 '+duration(now-start):'';}
function renderTaskElapsed(){const target=$('task-elapsed'),current=state.current,text=current?taskElapsed(current.detail.task,current.detail.runs,current.detail.summary):'';target.textContent=text;target.hidden=!text;}
function tokens(value){const n=Number(value||0);if(n<1000)return n.toLocaleString();if(n<1e6)return(n/1e3).toLocaleString(undefined,{maximumFractionDigits:1})+'K';return(n/1e6).toLocaleString(undefined,{maximumFractionDigits:2})+'M';}
function renderTokenUsage(usage){const box=$('token-usage');box.replaceChildren();const headline=node('div',null,'token-total'),main=node('div');main.append(node('span','TOKEN 开销','eyebrow'),node('strong',tokens(usage?.total_tokens||0)));const covered=usage?.reported_runs||0,total=usage?.run_count||0;main.append(node('span',covered?`输入 ${tokens(usage.input_tokens)} · 输出 ${tokens(usage.output_tokens)} · 缓存输入 ${tokens(usage.cached_input_tokens)}`:'尚未收到 Agent 的 Token 报告','token-total-meta'));headline.append(main);const details=node('details',null,'token-details');details.append(node('summary',covered?'按工作环节查看':'查看统计说明'));if(covered){const stages=node('div',null,'token-stages'),order=['planning','development','review','testing','acceptance','consultation','other'];for(const stage of [...(usage.stages||[])].sort((a,b)=>order.indexOf(a.stage)-order.indexOf(b.stage))){const item=node('details',null,'token-stage'),summary=node('summary');summary.append(node('span',stage.label),node('strong',tokens(stage.total_tokens)));item.append(summary,node('p',`输入 ${Number(stage.input_tokens).toLocaleString()} · 输出 ${Number(stage.output_tokens).toLocaleString()} · 缓存输入 ${Number(stage.cached_input_tokens).toLocaleString()} · 推理输出 ${Number(stage.reasoning_output_tokens).toLocaleString()}`,'small muted'));for(const run of stage.runs||[]){const row=node('div',null,'token-run');row.append(node('span',run.task_title||run.task_id),node('span',`${tokens(run.total_tokens)} · ${run.provider}${run.model_id?' · '+run.model_id:''} · ${run.turns} 轮`));item.append(row);}stages.append(item);}details.append(stages);}const missing=usage?.unreported_runs||0,pending=usage?.pending_runs||0;if(missing||pending){const parts=[];if(missing)parts.push(`${missing} 次已结束运行未报告 usage`);if(pending)parts.push(`${pending} 次运行尚未结束`);details.append(node('p',parts.join('；')+'。总数只包含 Agent 实际报告的数据，不把缺失值当成 0。','small token-coverage'));}else if(covered){details.append(node('p',`已覆盖 ${covered}/${total} 次运行；总数包含当前任务及其子任务、评审任务。`,'small muted'));}headline.append(details);box.append(headline);}
function summaryList(parent,title,items){if(!items?.length)return;parent.append(node('h3',title));const list=node('ul');for(const item of items)list.append(node('li',item));parent.append(list);}
function key(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';$('notice').hidden=!text;}
function headers(){return state.token?{Authorization:'Bearer '+state.token}:{};}
async function api(path,method='GET',body){const r=await fetch('/api/v1'+path,{method,headers:{...headers(),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(r.status===401?'请在连接设置中填写 API Token。':value.error||'请求失败');return value;}
async function action(fn){if(state.busy||state.loading||reviewChat.isBusy())return;state.busy=true;controls();notice('');try{await fn();}catch(e){notice(e.message,true);}finally{state.busy=false;controls();}}
function controls(){renderRetry();document.querySelectorAll('button').forEach(b=>b.disabled=state.busy||state.loading);reviewChat.controls(state.busy);activity.controls();assignment.controls(state.busy||state.loading);if(!state.current)return;const done=state.current.detail.task.state==='COMPLETED',active=state.current.detail.runs.some(r=>['RUNNING','QUEUED'].includes(r.state)),pending=state.current.work.reviews.find(r=>r.state==='PENDING');$('composer').hidden=done||!!pending;$('pause').disabled=state.busy||state.loading||done||state.current.work.config.paused||state.current.detail.task.state==='NEW';$('steer').disabled=state.busy||state.loading||!active;$('download').disabled=state.busy||state.loading||!state.current.work.artifacts.length;const blocked=state.busy||state.loading||reviewChat.isBusy()||reviewChat.isWaiting()||reviewChat.hasDraft()||!pending,testsBlocked=pending?.kind!=='plan'&&WATestPipelines.blocked(state.current.work.test_pipelines||[]);$('approve').disabled=blocked||testsBlocked;$('approve').title=testsBlocked?'最新 PR 版本的 QA 回归尚未通过，请查看回归测试记录':'';$('reject').disabled=blocked;}
function retryAvailable(data){const latest=[...(data?.detail.runs||[])].sort((a,b)=>b.created_at_ms-a.created_at_ms)[0],retryable=(data?.detail.task.state==='BLOCKED'&&['FAILED','COMPLETED'].includes(latest?.state))||data?.detail.task.state==='PAUSED';return retryable&&!data.detail.runs.some(r=>['RUNNING','QUEUED'].includes(r.state))&&!data.work.reviews.some(r=>r.state==='PENDING')&&(!data.work.development||['PLANNING','IMPLEMENTING'].includes(data.work.development.phase));}
function renderRetry(){const button=$('retry-work'),paused=state.current?.detail.task.state==='PAUSED';button.textContent=paused?'恢复执行':'重新评估 / 继续';button.title=paused?'沿用原 Agent、原 Session、当前阶段和已批准方案继续':'沿用原 Agent、原 Session 和当前阶段重新评估受阻原因；不重放已有外部操作';button.hidden=!retryAvailable(state.current);button.disabled=state.busy||state.loading||button.hidden;}
function option(value,label){const o=node('option',label);o.value=value;return o;}
function options(select,items,field,label,empty){const old=select.value;select.replaceChildren(option('',empty));for(const item of items)select.append(option(item[field],label(item)));select.value=old;}
async function library(){const [roles,agents,projects,system]=await Promise.all([api('/roles'),api('/agents'),api('/projects'),api('/system')]);state.roles=roles.roles;state.agents=agents.agents;state.projects=projects.projects;state.runtimes=system.runtimes||[];options($('new-role'),state.roles,'role_id',r=>r.name+' · v'+r.version,'任意合适角色');updateCreationAgents();options($('new-project'),state.projects,'project_id',p=>p.name,'不附加团队资料');$('health').textContent=system.eligible_agents?`${system.connected_runtimes} 台在线 · ${system.eligible_agents} 个可用 Agent`:'未就绪：请在成员管理页配置在线 Agent';activity.update(state.current,state.agents,state.runtimes);assignment.update(state.current,state.agents,state.runtimes);}
function visibleTasks(){const q=$('search').value.trim().toLowerCase(),filter=$('filter').value;return state.tasks.filter(t=>WATaskHierarchy.matchesFilter(t,filter)&&(!q||(t.title+' '+t.goal).toLowerCase().includes(q)));}
function appendProgress(parent,t){const text=WATaskHierarchy.progressText(t);if(text){const hint=node('small',text,'work-subtasks');hint.dataset.attention=String(!!t.subtasks?.needs_attention);parent.append(hint);}}
function taskDisplayState(t){const item=state.tasks.find(candidate=>candidate.task_id===t.task_id);return WATaskHierarchy.displayState({...item,...t,subtasks:t.subtasks||item?.subtasks});}
function renderList(){const tasks=visibleTasks();$('task-list').replaceChildren();if(!tasks.length)$('task-list').append(node('p','没有符合条件的原始任务。','empty'));for(const t of tasks){const active=t.task_id===state.id||state.current?.hierarchy?.roots.some(r=>r.task_id===t.task_id),display=taskDisplayState(t),elapsed=taskElapsed(t);const b=node('button',null,'task-item'+(active?' active':''));b.append(node('strong',t.title),node('small',(labels[display]||display)+' · '+new Date(Math.max(t.updated_at_ms,t.subtasks?.updated_at_ms||0)).toLocaleString()));if(elapsed)b.append(node('small',elapsed,'task-elapsed'));appendProgress(b,t);b.onclick=()=>action(()=>selectTask(t.task_id));$('task-list').append(b);}}
async function list(){state.tasks=(await api('/work/tasks?scope=roots')).tasks;renderList();renderWorkOverview();}
async function selectTask(id){
 const switching=state.id!==id;
 if(switching&&($('message').value||$('review-comment').value||reviewChat.hasDraft())&&!confirm('放弃尚未发送的消息或验收意见，切换任务？')){history.replaceState(null,'',state.id?'#'+state.id:'/tasks');return;}
 const [current,relations]=await Promise.all([api('/work/tasks/'+encodeURIComponent(id)+'?event_limit=30'),api('/work/tasks/'+encodeURIComponent(id)+'/hierarchy')]);
 if(switching){reviewChat.reset();state.artifactID='';state.messageKey='';$('message').value='';$('review-comment').value='';}
 current.hierarchy=relations;state.current=current;state.id=id;history.replaceState(null,'','#'+id);renderTask();renderList();const development=current.work.development||{},manualCapability={available:current.detail.task.state==='BLOCKED'&&development.phase==='IMPLEMENTING'&&!!development.approved_review_id&&!!development.plan_hash&&!!development.repository&&!!current.detail.session,expected_version:current.detail.task.version,runtime_id:current.detail.session?.runtime_id||'',repository:development.repository||''};await Promise.all([consultation.update(id),taskPermissions.update(id,current.detail.task.state,manualCapability)]);
}
function renderTask(){const {detail,work}=state.current,t=detail.task,presentation=WATaskReferences.presentation(t,work),display=taskDisplayState(t);WATaskReferences.render($('task-references'),work.references);$('welcome').hidden=true;$('task').hidden=false;$('title').textContent=presentation.title;$('goal').textContent=presentation.goal;$('status').textContent=labels[display]||display;$('status').dataset.state=display;renderTaskElapsed();const owner=state.agents.find(a=>a.agent_id===t.assigned_agent_id);const preferred=state.agents.find(a=>a.agent_id===work.config.preferred_agent_id);$('owner').textContent=owner?owner.name+' · '+(detail.session?.model_id||'默认模型'):preferred?preferred.name+' · 等待执行':t.state==='NEW'?'待分派':'自动分派中';$('session').textContent=detail.session?JSON.stringify({task_id:t.task_id,agent_id:detail.session.agent_id,session_id:detail.session.session_id,native_session:detail.session.agent_session_ref,runtime:detail.session.runtime_id,role_version:detail.runs[0]?.role_snapshot?.version,team_material:work.config.project.name||'未附加团队资料',mode:'只读执行 · 本地产物'},null,2):'首次调度后建立 Session。';$('scheduler-error').hidden=!work.config.scheduler_error;$('scheduler-error').textContent='等待调度 / 需要处理：'+work.config.scheduler_error;
 renderTokenUsage(work.token_usage);
 $('goal').replaceChildren(markdown(presentation.goal));
 renderPlanChange(detail);
 renderPendingInput(t,work);
 const box=$('messages'),nearBottom=box.scrollTop+box.clientHeight>=box.scrollHeight-60;box.replaceChildren();for(const m of work.messages){const b=node('div',null,'bubble '+m.speaker);b.append(node('span',(m.speaker==='user'?'你':m.speaker==='assistant'?(owner?.name||'Agent'):'系统')+' · '+new Date(m.created_at_ms).toLocaleTimeString(),'speaker'),markdown(WATaskReferences.message(t,work,m)));if(m.delivery==='PENDING')b.append(node('div','已保存 · 等待下一轮处理','delivery'));box.append(b);}if(nearBottom)box.scrollTop=box.scrollHeight;
 const review=work.reviews.find(r=>r.state==='PENDING');if(review?.review_id&&review.review_id!==$('review').dataset.reviewId){state.artifactID=review.artifact_ids[0]||'';$('review-comment').value='';}$('review').hidden=!review;$('review').dataset.reviewId=review?.review_id||'';renderPendingReview(review,work);
 let reasonBox=$('blocked-reason');if(!reasonBox){reasonBox=node('section',null,'panel warning prewrap');reasonBox.id='blocked-reason';$('scheduler-error').after(reasonBox);}reasonBox.hidden=t.state!=='BLOCKED';reasonBox.replaceChildren();if(t.state==='BLOCKED'){const latest=[...detail.runs].sort((a,b)=>b.created_at_ms-a.created_at_ms)[0];let result;try{result=JSON.parse(latest?.output||'{}');}catch{result={};}const reason=work.config.scheduler_error||latest?.error||result.task_update?.blocked_reason||result.message||'没有结构化受阻原因，请查看任务对话和运行记录。';reasonBox.append(node('h3','当前受阻原因'),node('p',reason));if(result.task_update?.analysis)reasonBox.append(node('p','诊断：'+result.task_update.analysis));}
 const dev=work.development,isPlan=review?.kind==='plan';
 $('approve').textContent=isPlan?'批准方案，开始开发':'验收通过';
 $('review-heading').textContent=isPlan?'方案待你确认':'本次提交待你验收';
 let phaseBox=$('development-phase');
 phaseBox.hidden=!dev;phaseBox.replaceChildren();
 if(dev){const phase=dev.phase==='IMPLEMENTING'&&t.state==='WAITING_REVIEW'?'等待最终验收':({PLANNING:'形成 / 修订方案',AGENT_REVIEW:'Agent 方案互审',HUMAN_REVIEW:'等待你确认方案',IMPLEMENTING:'开发 / PR 反馈处理'}[dev.phase]||dev.phase);
 phaseBox.append(node('h3',phase),node('p','方案 → Agent 互审 → 你确认 → 开发与验证 → PR 评审 → 最终验收','small muted'));
 if(dev.repository)phaseBox.append(node('p','待审批 / 已批准范围：'+dev.repository+' · '+dev.base_branch,'small'));
 if(dev.plan_hash)phaseBox.append(node('p','方案版本 '+dev.version+' · SHA-256 '+dev.plan_hash,'small'));
 renderValidationPlan(phaseBox,dev.validation_plan);
 if(dev.reviewer_task_id){const a=node('a','查看方案 reviewer 的工作与讨论');a.href='/tasks#'+dev.reviewer_task_id;phaseBox.append(a);}
 }
 const directionMode=dev?.phase==='IMPLEMENTING';$('message-mode-label').hidden=!directionMode;if($('message-mode').dataset.task!==t.task_id){$('message-mode').dataset.task=t.task_id;$('message-mode').value=directionMode?'execution_direction':'plan_change';}else if(!directionMode)$('message-mode').value='plan_change';$('message-mode-hint').textContent=directionMode?($('message-mode').value==='execution_direction'?'执行方向会沿用当前已批准方案和权限；选择“方案/需求变更”才会重新评审。':'方案或需求变更会停止当前实施并重新进入方案评审。'):'发送：当前轮结束后处理。打断并发送：请求停止当前轮后继续；不是回滚。';
 assignment.update(state.current,state.agents,state.runtimes);
 hierarchy.update(state.current,state.agents,state.roles);
 WATestPipelines.render($('test-pipelines'),work.test_pipelines||[],{resolve:p=>action(async()=>{if(!confirm('请先在 GitLab 按申请标识核查，确认没有创建对应流水线。重置后 Agent 可以申请重试；如果判断错误，可能重复运行测试。确认未创建？'))return;const result=await api('/work/tasks/'+encodeURIComponent(p.task_id)+'/test-pipelines/'+encodeURIComponent(p.request_id)+'/resolve','POST',{confirm_not_created:true});await selectTask(state.id);await list();notice(result.status==='recovered'?'已找回原 pipeline 并恢复轮询，没有重跑。':'核查确认已记录，原 Agent 可以分析后显式重试。');})});
 WATestPipelines.renderPublications($('publications'),work.publications||[],{resolve:p=>action(async()=>{if(!confirm('确认已在原页面检查，没有创建这条评论？系统会先再次核对；只有完整查询仍未找到时才允许重试。判断错误可能导致重复评论。'))return;const result=await api('/work/tasks/'+encodeURIComponent(p.task_id)+'/publications/'+encodeURIComponent(p.key)+'/resolve','POST',{confirm_not_created:true});await selectTask(state.id);notice(result.status==='recovered'?'已找回原评论，没有重复发布':result.message||result.status);})});
 $('send').textContent=t.state==='NEW'?'保存补充要求':'发送 / 继续';
 renderSummary(detail.summary,t);
 if(detail.summary?.executor)$('summary-body').append(node('p','最终交付执行配置 · '+executionLabel(detail.summary.executor),'small muted'));
 reviewChat.update({...state.current,agents:state.agents});
 activity.update(state.current,state.agents,state.runtimes);
 const old=state.artifactID,sel=$('artifact');sel.replaceChildren();for(const a of work.artifacts)sel.append(option(a.artifact_id,`${a.name} · v${a.version}${review?.artifact_ids.includes(a.artifact_id)?' · 本次验收':''}`));state.artifactID=work.artifacts.some(a=>a.artifact_id===old)?old:(work.artifacts[0]?.artifact_id||'');sel.value=state.artifactID;renderArtifact();
 $('runs').replaceChildren();for(const r of detail.runs.slice(-10).reverse())$('runs').append(node('p',`${r.run_id}\n${runStateLabel(r.state)} · ${r.adapter_id} · ${r.model_id||'默认模型'} · ${executionLabel(r)}${r.error?'\n'+r.error:''}`,'prewrap'));
 $('events').textContent=detail.events.slice(-30).map(e=>`${new Date(e.occurred_at_ms).toLocaleTimeString()} ${e.event_type}\n${e.payload.message||e.payload.error||''}`).join('\n');$('reviews').replaceChildren();for(const r of work.reviews){const row=node('details');row.append(node('summary',`${r.state} · ${r.review_id}`),node('p',r.comment||'没有正式验收意见','prewrap'));for(const turn of (work.review_turns||[]).filter(t=>t.review_id===r.review_id)){row.append(node('p','你：'+turn.question,'prewrap'));if(turn.answer)row.append(node('p','交付 Agent：'+turn.answer,'prewrap'));if(turn.error)row.append(node('p',turn.error,'small error'));} $('reviews').append(row);}controls();}
function renderSummary(summary,task){const body=$('summary-body');body.replaceChildren();if(!summary){$('summary-state').textContent='待生成';body.append(node('p',task.state==='COMPLETED'?'这件历史工作尚无总结。':'任务完成并验收通过后，系统会自动汇总结果、耗时、等待、返工和可复用经验。','summary-empty'));return;}$('summary-state').textContent=`v${summary.version} · ${WA.date(summary.completed_at_ms)}`;body.append(markdown(summary.result,'summary-result markdown-body'));const m=summary.metrics,grid=node('div',null,'summary-metrics');for(const [label,value] of [['总周期',duration(m.cycle_time_ms)],['Agent 运行',duration(m.active_run_time_ms)],['排队等待',duration(m.queue_wait_ms+m.runtime_queue_wait_ms)],['等待验收',duration(m.human_review_wait_ms)]]){const card=node('div');card.append(node('strong',value),node('span',label));grid.append(card);}body.append(grid);const details=node('details',null,'summary-details');details.append(node('summary','展开效率明细'));const who=[summary.executor.role_name,summary.executor.agent_id,summary.executor.model_id].filter(Boolean).join(' · ');if(who)details.append(node('p','执行：'+who,'small muted'));details.append(node('p',`运行 ${m.run_count} 轮（失败 ${m.failed_run_count} / 中断 ${m.interrupted_run_count}） · 验收 ${m.review_round_count} 轮（打回 ${m.changes_requested_count}） · 补充/改向 ${m.guidance_message_count} 次 · 交付 ${m.deliverable_count} 个文件 / ${m.artifact_version_count} 个版本${m.subtask_count?` · 子任务 ${m.completed_subtask_count}/${m.subtask_count} 完成`:''}`,'small'));if(summary.acceptance_comment)details.append(markdown('**最终验收意见：** '+summary.acceptance_comment,'small markdown-body'));summaryList(details,'可复用经验',summary.learnings);summaryList(details,'Agent 建议的改进',summary.improvements);if(summary.efficiency_signals?.length){details.append(node('h3','系统识别的效率信号'));const list=node('ul');for(const signal of summary.efficiency_signals){const item=node('li');item.append(node('strong',signal.evidence+'：'),document.createTextNode(signal.suggestion));list.append(item);}details.append(list);}if(summary.accepted_artifacts?.length)summaryList(details,'最终验收的交付物',summary.accepted_artifacts.map(a=>`${a.name} · v${a.version}`));body.append(details);}
function renderArtifact(){const a=state.current?.work.artifacts.find(a=>a.artifact_id===state.artifactID),preview=$('preview');preview.replaceChildren();preview.className='artifact-preview';if(!a)preview.textContent='Agent 提交后，文件会出现在这里。';else if(/\.(md|markdown)$/i.test(a.name))preview.append(markdown(a.content));else{preview.classList.add('plain-text');preview.textContent=a.content;}$('artifact-info').textContent=a?`v${a.version} · ${new Date(a.created_at_ms).toLocaleString()} · SHA-256 ${a.sha256}`:'';$('download').disabled=!a;}
async function download(path,filename){const r=await fetch('/api/v1'+path,{headers:headers()});if(!r.ok)throw Error('下载失败：'+r.status);const url=URL.createObjectURL(await r.blob()),a=node('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function createDialog(){state.createKey=key();updateCreationMode(); $('create-dialog').showModal();$('new-title').focus();}
$('new').onclick=createDialog;$('welcome-new').onclick=createDialog;$('close-dialog').onclick=()=>$('create-dialog').close();
$('search').oninput=()=>{renderList();renderWorkOverview();};$('filter').onchange=()=>{renderList();renderWorkOverview();};$('artifact').onchange=()=>{state.artifactID=$('artifact').value;renderArtifact();};
function updateCreationAgents(){const select=$('new-agent'),old=select.value;select.replaceChildren(option('','选择执行成员'));const requirements={role_id:$('new-role').value,capabilities:$('new-capabilities').value.split(',').map(c=>c.trim()).filter(Boolean)};for(const item of WAAssignment.candidates(requirements,state.agents,state.runtimes)){const o=option(item.value,item.label);o.disabled=item.disabled;select.append(o);}select.value=[...select.options].some(o=>o.value===old)?old:'';}
function updateCreationMode(){const mode=$('new-assignment-mode').value;$('new-agent-label').hidden=mode!=='member';$('new-agent').required=mode==='member';$('new-agent').disabled=mode!=='member';$('create').textContent=mode==='later'?'创建任务 →':mode==='member'?'创建并交给指定成员 →':'创建并自动分派 →';$('new-assignment-note').textContent=mode==='later'?'先保存任务，创建后在“执行安排”中选择成员或自动分派。':mode==='member'?'指定成员忙碌或离线时留在队列等待，不自动换人。':'由当前路由配置按角色、能力、在线状态和容量选择；没有合适成员时等待。';updateCreationAgents();}
$('new-role').onchange=updateCreationAgents;$('new-capabilities').oninput=updateCreationAgents;$('new-assignment-mode').onchange=updateCreationMode;
$('attachments').onchange=async()=>{try{const files=[...$('attachments').files];if(files.reduce((sum,f)=>sum+f.size,0)>24000)throw Error('附件总计最多 24 KB。');const parts=[];for(const f of files){const content=await f.text();if(content.includes('\u0000'))throw Error('只支持 UTF-8 文本文件。');parts.push(`附件 ${f.name}:\n${content}`);}state.files=parts.length?'\n\n'+parts.join('\n\n'):'';$('attachment-info').textContent=files.map(f=>f.name).join('、');}catch(e){state.files='';$('attachments').value='';$('attachment-info').textContent='';notice(e.message,true);}};
$('create-form').onsubmit=e=>{e.preventDefault();action(async()=>{const mode=$('new-assignment-mode').value;const t=await api('/work/tasks','POST',{title:$('new-title').value,goal:$('new-goal').value+state.files,requirements:{role_id:$('new-role').value,capabilities:$('new-capabilities').value.split(',').map(x=>x.trim()).filter(Boolean)},defer_assignment:mode==='later',agent_id:mode==='member'?$('new-agent').value:'',project_id:$('new-project').value,idempotency_key:state.createKey});$('create-dialog').close();$('create-form').reset();updateCreationMode();state.files='';$('attachment-info').textContent='';$('message').value='';$('review-comment').value='';state.artifactID='';await list();await selectTask(t.task_id);notice(mode==='later'?'任务已保存，请在“执行安排”中指定成员或自动分派。':mode==='member'?'任务已保存，等待指定成员执行。':'任务已保存，正在自动分派。');});};
$('save-project').onclick=()=>action(async()=>{const p=await api('/projects','POST',{name:$('project-name').value,context:$('project-context').value});await library();$('new-project').value=p.project_id;$('project-name').value='';$('project-context').value='';notice('团队资料已保存。');});
function send(interrupt){action(async()=>{const message=$('message').value.trim(),mode=$('message-mode-label').hidden?'plan_change':$('message-mode').value;if(!message)throw Error('请先填写下一步要求。');if(!state.messageKey)state.messageKey=key();await api('/work/tasks/'+state.id+'/messages','POST',{message,interrupt,mode,idempotency_key:state.messageKey});state.messageKey='';$('message').value='';$('review-comment').value='';await selectTask(state.id);await list();notice(state.current.detail.task.state==='NEW'?'补充要求已保存；选择执行安排后再开始工作。':mode==='execution_direction'?(interrupt?'执行方向已保存，正在安全中断；随后沿用原方案和 Session 继续。':'执行方向已保存，将在下一轮沿用原方案处理。'):interrupt?'方案变更已保存，正在停止当前轮并重新评审。':'方案变更已保存，将重新进入方案评审。');});}
$('message').oninput=()=>{state.messageKey='';};$('message-mode').onchange=()=>{state.messageKey='';$('message-mode-hint').textContent=$('message-mode').value==='execution_direction'?'执行方向会沿用当前已批准方案和权限；选择“方案/需求变更”才会重新评审。':'方案或需求变更会停止当前实施并重新进入方案评审。';};$('send').onclick=()=>send(false);$('steer').onclick=()=>send(true);
$('pending-input-reply').onclick=()=>{$('message').scrollIntoView?.({behavior:'smooth',block:'center'});$('message').focus();};
$('pending-review-open').onclick=()=>{const review=state.current?.work.reviews.find(item=>item.state==='PENDING');if(!review)return;const artifactID=(review.artifact_ids||[]).find(id=>state.current.work.artifacts.some(item=>item.artifact_id===id));if(artifactID){state.artifactID=artifactID;$('artifact').value=artifactID;renderArtifact();}$('review-delivery').scrollIntoView?.({behavior:'smooth',block:'start'});$('approve').focus();};
WA.bindChatInput?.($('message'),()=>$('send').click());
$('consultation-open').onclick=()=>consultation.open();
$('retry-work').onclick=()=>action(async()=>{const id=state.id,version=state.current.detail.task.version,paused=state.current.detail.task.state==='PAUSED';try{await api('/work/tasks/'+id+'/retry','POST',{expected_version:version});await selectTask(id);await list();notice(paused?'已恢复调度，沿用原 Agent、原 Session、当前阶段和已批准方案继续。':'已请求重试，沿用原 Agent、原 Session 和当前方案；不会重新设计。');}catch(e){await selectTask(id);throw e;}});
$('pause').onclick=()=>action(async()=>{await api('/work/tasks/'+state.id+'/pause','POST',{});await selectTask(state.id);await list();});
function review(decision){action(async()=>{if(reviewChat.hasDraft()||reviewChat.isWaiting())throw Error('请先完成验收沟通并处理未发送的问题。');const reviewID=$('review').dataset.reviewId,r=state.current.work.reviews.find(r=>r.review_id===reviewID);if(decision==='APPROVED'&&r.kind==='plan')decision='PLAN_APPROVED';await api('/work/tasks/'+state.id+'/reviews/'+reviewID,'POST',{decision,comment:$('review-comment').value,expected_discussion_version:r.discussion_version||0});$('review-comment').value='';await selectTask(state.id);await list();notice(decision==='PLAN_APPROVED'?'方案已批准，原 Agent 将开始隔离开发。':decision==='APPROVED'?'已验收，任务完成并已生成总结。':'修改意见已保存，将回到原 Agent / Session。');});}
$('approve').onclick=()=>review('APPROVED');$('reject').onclick=()=>review('CHANGES_REQUESTED');
$('download').onclick=()=>action(async()=>{const a=state.current.work.artifacts.find(a=>a.artifact_id===state.artifactID);if(a)await download('/work/tasks/'+state.id+'/artifacts/'+a.artifact_id,a.name);});
$('backup').onclick=()=>action(async()=>{await download('/admin/backup','work-assistant-'+new Date().toISOString().replace(/[:.]/g,'-')+'.sqlite');notice('备份包含任务、总结、对话、角色版本、团队资料、产物和验收记录；不包含各机器的原生 Agent Session 文件或仓库。');});
$('connect').onclick=()=>action(async()=>{WA.saveToken($('token').value);state.token=WA.token();await library();await list();if(state.id){await selectTask(state.id);activity.reconnect();}notice('已连接，Token 仅保存在此标签页会话中，页面切换时仍可使用。');});
window.addEventListener('beforeunload',e=>{if($('message').value||$('review-comment').value||reviewChat.hasDraft()){e.preventDefault();e.returnValue='';}});
async function refreshFromEvent(){activityRefresh=null;if(!state.id)return;if(state.busy||state.loading||reviewChat.isBusy()||$('create-dialog').open){activityRefresh=setTimeout(refreshFromEvent,500);return;}state.loading=true;try{await selectTask(state.id);await list();}catch(e){notice(e.message+'，稍后重试读取状态。',true);}finally{state.loading=false;controls();}}
async function poll(){if(!state.busy&&!state.loading&&!reviewChat.isBusy()&&!$('create-dialog').open){state.loading=true;try{await list();if(state.id){const relations=await api('/work/tasks/'+encodeURIComponent(state.id)+'/hierarchy');if(!activity.isConnected()||relations.task_version!==state.current?.detail.task.version)await selectTask(state.id);else state.current.hierarchy=relations;}await library();hierarchy.update(state.current,state.agents,state.roles);renderList();renderTaskElapsed();}catch(e){notice(e.message+'，稍后重试读取状态。',true);}finally{state.loading=false;controls();}}setTimeout(poll,5000);}
function renderWorkOverview(){
 const counts=$('work-counts');counts.replaceChildren();
 for(const [title,bucket] of [['等待队列','queued'],['推进中','active'],['需要你','attention'],['已完成','completed']]){const n=node('div');n.append(node('strong',state.tasks.filter(t=>WATaskHierarchy.bucket(t)===bucket).length),node('span',title));counts.append(n);}
 const q=$('search').value.trim(),f=$('filter').value,tasks=visibleTasks();
 $('work-list-count').textContent=tasks.length+' 件原始任务';$('work-list-heading').textContent=f==='QUEUED'?'等待队列':f?(labels[f]||f):q?'搜索结果':'全部工作';$('work-table').replaceChildren();
 for(const t of tasks){
  const b=node('button',null,'work-table-row'),title=node('div'),status=node('div',null,'work-task-status');
  title.append(node('strong',t.title),node('small',t.goal.length>65?t.goal.slice(0,65)+'…':t.goal));appendProgress(title,t);status.append(WA.badge(taskDisplayState(t)));
  const elapsed=taskElapsed(t);if(elapsed)status.append(node('small',elapsed,'task-elapsed'));
  if(t.subtasks?.needs_attention)status.append(node('small','子任务需要你','hierarchy-attention'));
  b.append(title,status,node('span',state.agents.find(a=>a.agent_id===(t.assigned_agent_id||t.preferred_agent_id))?.name||(t.state==='NEW'?'待分派':'自动分派中'),'muted'),node('span',WA.date(Math.max(t.updated_at_ms,t.subtasks?.updated_at_ms||0)),'muted'));
  b.onclick=()=>action(()=>selectTask(t.task_id));$('work-table').append(b);
 }
 if(!tasks.length)$('work-table').append(node('p',q||f?'没有符合条件的原始任务。':'还没有工作。可以在首页与助理商量，也可以直接创建。','empty-state'));
}
$('back-to-list').onclick=()=>{if(($('message').value||reviewChat.hasDraft()||$('review-comment').value)&&!confirm('放弃尚未发送的消息或意见，返回工作列表？'))return;reviewChat.reset();consultation.reset();state.current=null;state.id='';activity.update(null);assignment.update(null);clearTimeout(activityRefresh);activityRefresh=null;state.messageKey='';$('message').value='';$('review-comment').value='';$('task').hidden=true;$('welcome').hidden=false;history.replaceState(null,'','/tasks');renderList();renderWorkOverview();};
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(id&&id!==state.id)action(()=>selectTask(id));});
window.addEventListener('pagehide',()=>{clearTimeout(activityRefresh);activity.dispose();taskPermissions.dispose();});
action(async()=>{await library();await list();const id=location.hash.slice(1);if(id)await selectTask(id);const project=new URLSearchParams(location.search).get('project');if(project&&state.projects.some(p=>p.project_id===project)){$('new-project').value=project;createDialog();}});setTimeout(poll,5000);
